mpKR = {
    m0: '모피모피 오버레이',
    m1: '전투를 시작하세요.',
    m7: '히스토리<i class="material-icons left" style="color: rgba(255,255,255,0.5)">history</i>',
    m3: '캐릭터 이름 숨기기<i class="material-icons left" style="color: rgba(255,255,255,0.5)">visibility_off</i>',
    m2: '힐러 ACT 보기<i class="material-icons left" style="color: rgba(255,255,255,0.5)">local_hospital</i>',
    m6: '전체 화면 모드<i class="material-icons left" style="color: rgba(255,255,255,0.5)">fullscreen</i>',
    m5: '설정<i class="material-icons left" style="color: rgba(255,255,255,0.5)">settings</i>',
    m10: '설정',
    m20: '커스터마이징',
    m11: '기본 ACT 구성',
    m30: '여러 항목을 조합해 나만의 ACT를 만들 수 있습니다.',
    m12: '힐러 ACT 구성',
    m31: '\'힐러 ACT 보기\' 체크 시 힐러 ACT에 출력할 항목들을 선택할 수 있습니다.',
    m21: '데이터 처리',
    m80: '소환수 데이터 합산하기',
    m81: '오버레이에서 유저와 소환수 데이터를 합산합니다.<br><font class="rdColor">= </font>소환사, 기공사, 학자',
    m170: '유저 그래프에 소환수 그래프 표시하기',
    m171: '유저 그래프에 소환수의 대미지량 또는 힐량 비율을 표시합니다.<br><font class="rdColor">= </font>소환수 데이터 합산하기 \'ON\'',
    m82: '숫자 데이터 유형',
    m83: '<font class="rdColor">OFF </font>정수<font class="rdColor">　　ON </font>소수',
    m84: '천 단위 구분 기호',
    m85: '<font class="rdColor">OFF </font>1234<font class="rdColor">　　ON </font>1,234',
    m207: '캐릭터 이름 표시 유형',
    m208: '풀네임으로 보기',
    m209: '성 단축하기',
    m210: '이름 단축하기',
    m211: '이니셜로 보기',
    m212: '순위 (DPS 기준)',
    m213: '<font class="rdColor">OFF </font>YOU<font class="rdColor">　　ON </font>1. YOU',
    m225: '글로벌 서버',
    m226: '오버레이의 숫자 또는 문자 데이터 유형을 설정합니다.',
    m227: '유럽 숫자 표기법 적용하기',
    m228: '숫자 데이터의 마침표(.)와 쉼표(,)를 서로 변경합니다.',
    m229: '기술명 단축',
    m230: '<font class="rdColor">OFF </font>미아즈마 버스트<font class="rdColor">　　ON </font>버스트',
    m233: '데이터 테이블 자동 숨기기',
    m234: '전투 집계가 끝나면 대기 시간 후에 데이터 테이블을 자동으로 숨깁니다.',
    m235: '기타 설정',
    m236: '기타 설정을 변경합니다.<br><font class="rdColor">= </font>오버레이, 데이터 테이블 등',
    m237: '오버레이 크기 조절 화살표',
    m238: '<font class="rdColor">OFF </font>숨기기<font class="rdColor">　　ON </font>보이기',
    m239: '데이터 테이블',
    m240: '메뉴 툴팁',
    m241: '토스트 메세지',
    m242: '<span class="PrimaryText">대기 시간</span><br><span class="SecondaryText"><font class="rdColor">= </font>단위 \'분\'</span>',
    m243: '백업',
    m244: '사용자 인터페이스 설정을 백업하거나 복원합니다. 또는 다른 사용자에게 설정값을 공유하거나 공유받습니다.',
    m245: '<span>마지막으로 백업한 일시<font id="backupDate" class="rdColor"></font></span>',
    m246: '복원',
    m247: '사용자 인터페이스 설정을 이전에 백업한 데이터로 복원합니다.',
    m248: '내 데이터',
    m249: '커스터마이징 공유하기',
    m250: '커스터마이징 적용하기',
    m251: '아래 값을 복사(Ctrl+C)합니다. 일부 설정값은 포함하지 않습니다.',
    m252: '적용할 값을 아래에 붙여 넣고(Ctrl+V), 엔터 키를 누릅니다.',
    m253: '백업 및 복원',
    m254: '이전에 백업한 데이터가 없습니다. 백업을 클릭해 데이터를 백업하십시오.',
    m255: '정말로 복원하시겠습니까?',
    m256: '인덱스',
    m257: '데이터 출력 순서',
    m258: '데이터 테이블의 \'열\' 순서를 변경합니다.',
    m259: '내 캐릭터 이름',
    m260: '<font class="rdColor">OFF </font>YOU<font class="rdColor">　　ON </font>예시) 해루',
    m261: '기술명 줄임말 관리',
    m262: '기술명 줄임말 데이터를 등록하거나 삭제합니다.',
    m263: '<br>1. PC 유저 : 한글 입력 시 메모장 등에 데이터를 입력하고 복사(Ctrl+C)후 붙여넣기(Ctrl+V)합니다.',
    m264: '등록하기',
    m265: '기술명 (띄어쓰기 주의)',
    m266: '줄임말',
    m267: '목록',
    m268: '확인',
    m269: '글자 정렬',
    m270: '<font class="rdColor">OFF </font>가운데<font class="rdColor">　　ON </font>왼쪽',
    m22: '디스플레이',
    m13: '언어',
    m14: '글꼴',
    m184: '글꼴 속성을 변경합니다.<br><font class="rdColor">= </font>글꼴, 크기, 색상, 스타일',
    m19: '네비게이션 바',
    m86: '네비게이션 바를 취향에 맞게 디자인합니다.',
    m23: '그래프',
    m87: '그래프 속성을 변경합니다.<br><font class="rdColor">= </font>색상, 효과, 불투명도',
    m16: '셀 너비',
    m91: '셀 너비를 그룹별로 조정합니다.',
    m24: '버전 및 개발자 정보',
    m150: '버전',
    m152: '문의하기',
    m153: 'ffxivHAERU@gmail.com',
    m200: '개발자 소개',
    m201: 'Thanks to :)',
    m25: '초기화',
    m26: '관리 도구',
    m162: '모든 설정을 기본값으로 복원합니다.',
    m163: '설정에 대한 모든 변경 사항이 기본값으로 복원되고 개인 데이터가 삭제됩니다. 초기화를 진행하시겠습니까?',
    m167: '새로고침',
    m168: '오버레이 동작이 원활하지 않을 때 사용합니다.<br>히스토리 내역이 삭제됩니다.',
    m90: '사용자 컴퓨터에 설치된 글꼴 파일로 서체를 변경합니다.<Br><font class="rdColor">= </font>Only PC',
    m102: '설정 전 주의사항',
    m103: '키보드로 직접 입력 시,<br>ACT > Plugins > ACTWebSocket > 오버레이 관리자 > 설정 > <b>"키 입력 무시" 체크 해제</b> 필수입니다.',
    m101: '<br>1. 글꼴명만 입력합니다. (글꼴 스타일 제외)<br>2. 글꼴 파일이 손상됐거나 글꼴명을 잘못 입력한 경우 기본값으로 적용됩니다.<br>3. 모바일 환경에서는 해당 기능을 지원하지 않습니다.<br>4. PC 유저 : 한글 입력 시 메모장 등에 데이터를 입력하고 복사(Ctrl+C)후 붙여넣기(Ctrl+V)합니다.',
    m96: '시간 (00:00)',
    m97: '일반',
    m98: '한국어',
    m99: '일본어',
    m104: '영어',
    m105: '독일어',
    m176: '크기',
    m177: '<span class="PrimaryText">글자 크기<br><span class="SecondaryText"><font class="rdColor">= </font>8px ~ 32px</span></span>',
    m129: '색상',
    m147: '<span class="PrimaryText">내 캐릭터<br><span class="SecondaryText"><font class="rdColor">= </font>YOU</span></span>',
    m148: '<span class="PrimaryText">타 캐릭터<br><span class="SecondaryText"><font class="rdColor">= </font>파티원</span></span>',
    m186: '내 캐릭터 글자 굵게',
    m187: '데이터 테이블의 내 캐릭터 글자를 굵게 표시합니다.',
    m188: '타 캐릭터 글자 굵게',
    m189: '데이터 테이블의 타 캐릭터 글자를 굵게 표시합니다.',
    m183: '<span class="PrimaryText">높이</span><br><span class="SecondaryText"><font class="rdColor">= </font>2씩 증감</span>',
    m100: '미리 보기',
    m190: '<span class="PrimaryText">배경색 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>네비게이션 바</span>',
    m172: '<span class="PrimaryText">강조색</span><br><span class="SecondaryText"><font class="rdColor">= </font>시간 (00:00), 아이콘</span>',
    m199: '<span class="PrimaryText">테두리색</span><br><span class="SecondaryText"><font class="rdColor">= </font>네비게이션 바</span>',
    m191: '<span class="PrimaryText">글자색 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>네비게이션 바<br><font class="rdColor">= </font>타겟 이름</span>',
    m192: '<span class="PrimaryText">글자색 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>네비게이션 바<br><font class="rdColor">= </font>RDPS, RHPS</span>',
    m219: '<span class="PrimaryText">배경색 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>테이블 헤더</span>',
    m222: '<span class="PrimaryText">글자색 3</span><br><span class="SecondaryText"><font class="rdColor">= </font>테이블 헤더</span>',
    m194: '모서리 둥글게 처리하기',
    m195: '네비게이션 바의 왼쪽, 오른쪽 상단 모서리를 둥글게 처리합니다.',
    m197: '테두리 그리기',
    m198: '네비게이션 바에 1px 테두리를 그립니다.',
    m181: '불투명도',
    m193: '상단바 불투명도',
    m221: '헤더 불투명도',
    m17: '그래프색',
    m119: '그래프색을 변경합니다.',
    m88: '구분선 긋기',
    m89: '그래프 사이사이에 구분선을 긋습니다.',
    m120: '그라데이션 효과 적용하기',
    m121: '그래프에 그라데이션 효과를 적용합니다.',
    m122: '애니메이션 전환 효과 사용하기',
    m123: 'DPS, HPS값 변동 시 그래프를 부드럽게 보여줍니다.',
    m15: '배경 불투명도',
    m18: '그래프 불투명도',
    m204: '효과',
    m217: '레이드 모드 활성화하기',
    m218: '전투원의 수가 9명을 초과할 경우, 데이터 테이블을 간략하게 표시합니다.',
    m109: '좁은 셀',
    m111: '좁은 셀 1',
    m112: '값의 변동폭이 낮은 셀<br><font class="rdColor">= </font>Job, D%, Death 등',
    m113: '좁은 셀 2',
    m114: 'DPS, HPS',
    m110: '넓은 셀',
    m115: '넓은 셀 1',
    m116: '값의 변동폭이 높은 셀<br><font class="rdColor">= </font>Damage, Healed 등',
    m117: '넓은 셀 2',
    m118: 'MaxHit, MaxHeal',
    m154: '모피모피 오버레이 스킨',
    m155: '한국 [모그리] 해루<br>GitHub <font class="rdColor">= </font>HAERUHAERU',
    m160: 'ACT 코어 라이브러리 : 참수크립트 (js/core.js)',
    m161: '한국 [모그리] 라그린네<Br>Elemental [Alexander] Lulala Lula<br>GitHub <font class="rdColor">= </font>laiglinne-ff',
    m156: '번역 (일본어)',
    m157: '한국 [모그리] 이카루가',
    m271: '번역 (독일어)',
    m272: 'Chaos [Phoenix] Shunittseru Tohka',
    m273: '번역 (중국어)/최적화',
    m274: '중국 [紫水栈桥] 幽兒希卡',
    m158: 'ACT 웹소켓 오버레이 플러그인',
    m159: '한국 [카벙클] 쿨냠쿨냠<br>GitHub <font class="rdColor">= </font>ZCube',
    m205: '내 캐릭터 색상 적용하기',
    m206: '내 캐릭터 그래프는 클래스 또는 직업과 관계없이 내 캐릭터(=YOU) 색상을 적용합니다.',
    m124: '탱커',
    m9: '색상 코드',
    m130: '<span class="PrimaryText">나이트</span><br><span class="SecondaryText"><font class="rdColor">= </font>검술사</span>',
    m131: '<span class="PrimaryText">전사</span><br><span class="SecondaryText"><font class="rdColor">= </font>도끼술사</span>',
    m132: '<span class="PrimaryText">암흑기사</span>',
    m125: '힐러',
    m133: '<span class="PrimaryText">백마도사</span><br><span class="SecondaryText"><font class="rdColor">= </font>환술사</span>',
    m134: '<span class="PrimaryText">학자</span>',
    m135: '<span class="PrimaryText">점성술사</span>',
    m165: '<span class="PrimaryText">대미지쉴드량</span><br><span class="SecondaryText"><font class="rdColor">= </font>힐러 ACT</span>',
    m166: '<span class="PrimaryText">오버힐량</span><br><span class="SecondaryText"><font class="rdColor">= </font>힐러 ACT</span>',
    m126: '딜러',
    m136: '<span class="PrimaryText">몽크</span><br><span class="SecondaryText"><font class="rdColor">= </font>격투사</span>',
    m137: '<span class="PrimaryText">용기사</span><br><span class="SecondaryText"><font class="rdColor">= </font>창술사</span>',
    m138: '<span class="PrimaryText">닌자</span><br><span class="SecondaryText"><font class="rdColor">= </font>쌍검사</span>',
    m231: '<span class="PrimaryText">사무라이</span>',
    m139: '<span class="PrimaryText">흑마도사</span><br><span class="SecondaryText"><font class="rdColor">= </font>주술사</span>',
    m140: '<span class="PrimaryText">소환사</span><br><span class="SecondaryText"><font class="rdColor">= </font>비술사</span>',
    m232: '<span class="PrimaryText">적마도사</span>',
    m141: '<span class="PrimaryText">음유시인</span><br><span class="SecondaryText"><font class="rdColor">= </font>궁술사</span>',
    m142: '<span class="PrimaryText">기공사</span>',
    m127: '채집 / 제작',
    m143: '<span class="PrimaryText">채집가</span><br><span class="SecondaryText"><font class="rdColor">= </font>3종</span>',
    m144: '<span class="PrimaryText">제작자</span><br><span class="SecondaryText"><font class="rdColor">= </font>8종</span>',
    m128: '기타',
    m145: '<span class="PrimaryText">리미트 브레이크</span><br><span class="SecondaryText"><font class="rdColor">= </font>Limit Break</span>',
    m169: '<span class="PrimaryText">소환수 데이터</span><br><span class="SecondaryText"><font class="rdColor">= </font>불투명도 50%<br><font class="rdColor">= </font>유저 그래프 위</span>',
    m146: '<span class="PrimaryText">초코보</span><br><span class="SecondaryText"><font class="rdColor">= </font>버디</span>',
    m220: '<span class="PrimaryText">배경색</span><br><span class="SecondaryText"><font class="rdColor">= </font>그래프 배경</span>',
    m223: '<span class="PrimaryText">구분선색</span><br><span class="SecondaryText"><font class="rdColor">= </font>구분선 긋기 \'ON\'</span>',
    m224: '구분선 불투명도',
    m32: '플레이어 정보',
    m33: '전투 항목',
    m34: '피격 항목',
    m35: '회복 항목',
    m36: '기타',
    m37: '순위 및 캐릭터 이름',
    m214: '캐릭터 이름',
    m38: '클래스 또는 직업 아이콘',
    m39: '전투 로그 수집 시간<br><font class="rdColor">= </font>내 첫 공격 기준',
    m40: '초당 딜량<br><font class="rdColor">= </font>P.Time 기준',
    m41: '전투 로그 수집 시간<br><font class="rdColor">= </font>파티 첫 공격 기준',
    m42: '초당 딜량<br><font class="rdColor">= </font>Time 기준, 공식',
    m43: '최근 10초간 평균 DPS',
    m44: '최근 30초간 평균 DPS',
    m45: '최근 60초간 평균 DPS',
    m46: '최근 180초간 평균 DPS',
    m47: '전체 딜량 중 내가 기여한 딜량 (%)',
    m48: '딜량',
    m49: '명중률 (%)',
    m50: '공격 횟수<br><font class="rdColor">= </font>자동 공격, 도트, 스킬 시전 취소 포함',
    m51: '공격 적중 횟수',
    m52: '공격 빗나감 횟수',
    m53: '공격 실패 횟수<br><font class="rdColor">= </font>적의 저항, 반사, 막기, 회피 등',
    m54: '공격 극대화 횟수',
    m55: '공격 극대화율 (%)',
    m56: '최대 공격 스킬',
    m57: '받은 피해량',
    m58: '받은 힐량',
    m59: '받아넘기기 발동률 (%)',
    m60: '방패막기 발동률 (%)',
    m61: '초당 힐량<br><font class="rdColor">= </font>Time 기준, 공식',
    m62: '전체 힐량 중 내가 기여한 힐량 (%)',
    m63: '총 힐량',
    m64: '유효힐량',
    m65: '대미지쉴드량<br><font class="rdColor">= </font>격려 효과, 밤의 보호',
    m66: '오버힐량',
    m67: '오버힐률 (%)',
    m68: '힐 횟수<br><font class="rdColor">= </font>도트, 스킬 시전 취소 포함',
    m69: '힐 극대화 횟수',
    m70: '힐 극대화율 (%)',
    m71: '최대 회복 스킬',
    m72: '디버프 해제 스킬 시전 횟수<br><font class="rdColor">= </font>에스나',
    m73: '스킬을 통한 HP 보충량<br><font class="rdColor">= </font>최후의 일격 등',
    m74: '스킬을 통한 MP 보충량<br><font class="rdColor">= </font>에테르 흡수 등',
    m75: '죽음 횟수',
    m76: 'Direct Hit 횟수',
    m77: 'Direct Hit 발동률 (%)',
    m78: 'Direct Hit 극대화 횟수',
    m79: 'Direct Hit 극대화율 (%)',
};
mpCN = {
    m0: 'MopiMopi Overlay',
    m1: '请开始战斗。',
    m7: '历史记录<i class="material-icons left" style="color: rgba(255,255,255,0.5)">history</i>',
    m3: '隐藏真实ID<i class="material-icons left" style="color: rgba(255,255,255,0.5)">visibility_off</i>',
    m2: 'Healer专属图表<i class="material-icons left" style="color: rgba(255,255,255,0.5)">local_hospital</i>',
    m6: '全屏模式<i class="material-icons left" style="color: rgba(255,255,255,0.5)">fullscreen</i>',
    m5: '设置<i class="material-icons left" style="color: rgba(255,255,255,0.5)">settings</i>',
    m10: '设置',
    m20: '自定义',
    m11: '基础数据内容',
    m30: '选择需要的数据来定制属于自己的图表。',
    m12: 'Healer数据内容',
    m31: '当“Healer专属图表”选中时，你可以定制治疗职业专属的数据图表。',
    m21: '数据处理',
    m80: '合并召唤兽数据',
    m81: '在数据图表中合并召唤兽和主人的数据。<br><font class="rdColor">= </font>对应召唤师、机工士、学者的宝宝',
    m170: '在用户图表中显示宠物图表',
    m171: '在用户图表中显示宠物的伤害或治疗比例。<br><font class="rdColor">= </font>需先激活“合并召唤兽数据”',
    m82: '数据数值类型',
    m83: '<font class="rdColor">OFF </font>整数<font class="rdColor">　　ON </font>小数',
    m84: '千分符',
    m85: '<font class="rdColor">OFF </font>1234<font class="rdColor">　　ON </font>1,234',
    m207: '名称显示类型',
    m208: '全名',
    m209: '缩短姓氏',
    m210: '缩短名字',
    m211: '首字母',
    m212: '显示排名',
    m213: '<font class="rdColor">OFF </font>YOU<font class="rdColor">　　ON </font>1. YOU',
    m215: '姓名',
    m225: '全局功能',
    m226: '设定数据图表中数字和字符的数据类型。',
    m227: '使用欧洲数字符号',
    m228: '改变小数点(.)和逗号(,)。',
    m229: '使用简短技能名',
    m230: '<font class="rdColor">OFF </font>纷乱雪月花<font class="rdColor">　　ON </font>雪月花',
    m233: '自动隐藏数据图表',
    m234: '战斗结束指定时间后自动隐藏图表。',
    m235: '其他设置',
    m236: '更改其他设置项。<br><font class="rdColor">= </font>模版、数据图表等。',
    m237: '模版大小调整箭头',
    m238: '<font class="rdColor">OFF </font>隐藏<font class="rdColor">　　ON </font>显示',
    m239: '数据图表',
    m240: '菜单按钮提示',
    m241: '提醒消息',
    m242: '<span class="PrimaryText">自动隐藏等待时间</span><br><span class="SecondaryText"><font class="rdColor">= </font>单位：分钟</span>',
    m243: '备份',
    m244: '你可以备份和恢复UI设置，或者分享给其他人。',
    m245: '<span>上次备份时间<font id="backupDate" class="rdColor"></font></span>',
    m246: '恢复',
    m247: '从现有数据中恢复设置。',
    m248: '我的数据',
    m249: '导出设置',
    m250: '导入设置',
    m251: '复制下面的内容（Ctrl+C），不包含某些特定选项。',
    m252: '在下面粘贴之前的备份内容，然后按回车键。',
    m253: '备份和恢复',
    m254: '没有数据，请点击“备份”来储存数据。',
    m255: '您真的要恢复吗？',
    m256: '索引',
    m257: '数据输出顺序',
    m258: '更改数据图表中每种数据的先后顺序',
    m259: '我的角色名字',
    m260: '<font class="rdColor">OFF </font>YOU<font class="rdColor">　　ON </font>神奇的海螺',
    m261: '简短技能名管理',
    m262: '你可以注册或者删除自定义简短技能名。',
    m263: '<br>PC用户：在记事本中输入数据并复制（Ctrl + C），然后粘贴（Ctrl + V）进来。',
    m264: '新增',
    m265: '技能名',
    m266: '缩写',
    m267: '现有缩写',
    m268: '提交',
    m269: '对齐格式',
    m270: '<font class="rdColor">OFF </font>关闭<font class="rdColor">　　ON </font>左',
    m22: '显示',
    m13: '语言',
    m14: '字体',
    m184: '更改字体属性。<br><font class="rdColor">= </font>字体、大小、颜色、样式',
    m19: '导航栏',
    m86: '设计导航栏来体现独到品味。',
    m23: '图表',
    m87: '更改图表属性。<br><font class="rdColor">= </font>颜色、效果、不透明度',
    m16: '单元宽度',
    m91: '更改组单元宽度。',
    m24: '版本和开发者信息',
    m150: '版本',
    m152: '联系我们',
    m153: 'ffxivHAERU@gmail.com',
    m200: '关于开发者',
    m201: 'Thanks to :)',
    m25: '还原',
    m26: '管理工具',
    m162: '使用该功能将所有选项恢复为默认设定。',
    m163: '所有的自定义设定会被重置，您的现有统计数据都将被删除。仍要继续初始化吗？',
    m167: '刷新',
    m168: '当模版功能异常时使用。<br>历史记录将被清除。',
    m90: '使用PC中安装好的其他字体<Br><font class="rdColor">= </font>仅限PC使用',
    m102: '进行设置前务必：',
    m103: 'ACT > 插件列表 > 美化模版管理器 > 呼出管理器 > Preference >勾选“No Focus”',
    m101: '<br>1. 你必须输入字体名称（字体样式除外）<br>2. 如果字体文件异常，将会使用默认设置。<br>3. 该功能不支持移动设备。<br>4. PC用户：输入中文时，在记事本中输入数据，复制（Ctrl + C）并粘贴（Ctrl + V）进来。',
    m96: '时间 (00:00)',
    m97: '总体',
    m98: '中文',
    m99: '日语',
    m104: '英文',
    m105: '德文',
    m176: '字号',
    m177: '<span class="PrimaryText">字号<br><span class="SecondaryText"><font class="rdColor">= </font>8px ~ 32px</span></span>',
    m129: '颜色',
    m147: '<span class="PrimaryText">用户<br><span class="SecondaryText"><font class="rdColor">= </font>YOU</span></span>',
    m148: '<span class="PrimaryText">其他人<br><span class="SecondaryText"><font class="rdColor">= </font>小队成员</span></span>',
    m186: '加粗用户字符',
    m187: '将表中用户数据加粗。',
    m188: '加粗他人字符',
    m189: '将表中他人数据加粗。',
    m183: '<span class="PrimaryText">高度</span><br><span class="SecondaryText"><font class="rdColor">= </font>每次更改增加或减少2个单位</span>',
    m100: '预览',
    m190: '<span class="PrimaryText">背景色 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>导航栏</span>',
    m172: '<span class="PrimaryText">强调色</span><br><span class="SecondaryText"><font class="rdColor">= </font>时间 (00:00), 图标</span>',
    m199: '<span class="PrimaryText">描边颜色</span><br><span class="SecondaryText"><font class="rdColor">= </font>导航栏</span>',
    m191: '<span class="PrimaryText">文本颜色 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>导航栏<br><font class="rdColor">= </font>目标名称</span>',
    m192: '<span class="PrimaryText">文本颜色 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>导航栏<br><font class="rdColor">= </font>RDPS, RHPS</span>',
    m219: '<span class="PrimaryText">背景颜色 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>表头</span>',
    m222: '<span class="PrimaryText">文本颜色 3</span><br><span class="SecondaryText"><font class="rdColor">= </font>表头</span>',
    m221: '表头不透明度',
    m194: '圆角',
    m195: '将导航栏边缘设置为圆角',
    m197: '边缘绘制',
    m198: '为导航栏添加1像素宽度的描边。',
    m181: '不透明度',
    m193: '导航栏不透明度',
    m17: '图表颜色',
    m119: '更换图表颜色',
    m88: '绘制分割线',
    m89: '在图表之间绘制分割线。',
    m120: '渐变效果',
    m121: '为图表添加渐变效果',
    m122: '使用动态过渡效果',
    m123: 'DPS, HPS数值改变时平滑过渡。',
    m15: '背景不透明度',
    m18: '图表不透明度',
    m204: '效果',
    m217: '激活Raid模式',
    m218: '战斗人数超过九名时简化显示。',
    m109: '狭窄单元',
    m111: '狭窄单元1',
    m112: '数值偶尔变化的单元<br><font class="rdColor">= </font>职业, 输出占比, 死亡次数等等',
    m113: '狭窄单元2',
    m114: 'DPS, HPS单元',
    m110: '宽广单元',
    m115: '宽广单元1',
    m116: '数值频繁变化的单元<br><font class="rdColor">= </font>伤害、治疗量等',
    m117: '宽广单元2',
    m118: 'MaxHit, MaxHeal 单元',
    m154: 'MopiMopi模版皮肤',
    m155: 'Korea [Moogle] Haeru<br>GitHub <font class="rdColor">= </font>HAERUHAERU',
    m160: 'ACT 核心库：Chamsucript (js/core.js)',
    m161: 'Korea [Moogle] Laiglinne<Br>Elemental [Alexander] Lulala Lula<br>GitHub <font class="rdColor">= </font>laiglinne-ff',
    m156: '日语本地化',
    m157: 'Korea [Moogle] Ikaruga',
    m271: '德语本地化',
    m272: 'Chaos [Phoenix] Shunittseru Tohka',
    m273: '中文本地化/优化',
    m274: '中国区 [紫水栈桥] 幽兒希卡',
    m158: 'ACT WebSocket插件',
    m159: 'Korea [Carbuncle] CoolnyamCoolnyam<br>GitHub <font class="rdColor">= </font>ZCube',
    m205: '应用一个用户颜色',
    m206: '使用用户指定的颜色，而非职业颜色',
    m124: '坦克',
    m9: '颜色代码',
    m130: '<span class="PrimaryText">骑士</span><br><span class="SecondaryText"><font class="rdColor">= </font>剑术师</span>',
    m131: '<span class="PrimaryText">战士</span><br><span class="SecondaryText"><font class="rdColor">= </font>斧术师</span>',
    m132: '<span class="PrimaryText">暗黑骑士</span>',
    m125: '治疗',
    m133: '<span class="PrimaryText">白魔法师</span><br><span class="SecondaryText"><font class="rdColor">= </font>幻术师</span>',
    m134: '<span class="PrimaryText">学者</span>',
    m135: '<span class="PrimaryText">占星术士</span>',
    m165: '<span class="PrimaryText">伤害吸收盾</span><br><span class="SecondaryText"><font class="rdColor">= </font>Healer数据</span>',
    m166: '<span class="PrimaryText">过量治疗</span><br><span class="SecondaryText"><font class="rdColor">= </font>Healer数据</span>',
    m126: '输出',
    m136: '<span class="PrimaryText">武僧</span><br><span class="SecondaryText"><font class="rdColor">= </font>格斗家</span>',
    m137: '<span class="PrimaryText">龙骑士</span><br><span class="SecondaryText"><font class="rdColor">= </font>枪术师</span>',
    m138: '<span class="PrimaryText">忍者</span><br><span class="SecondaryText"><font class="rdColor">= </font>双剑师</span>',
    m231: '<span class="PrimaryText">武士</span>',
    m139: '<span class="PrimaryText">黑魔法师</span><br><span class="SecondaryText"><font class="rdColor">= </font>咒术师</span>',
    m140: '<span class="PrimaryText">召唤师</span><br><span class="SecondaryText"><font class="rdColor">= </font>秘术师</span>',
    m232: '<span class="PrimaryText">赤魔法师</span>',
    m141: '<span class="PrimaryText">吟游诗人</span><br><span class="SecondaryText"><font class="rdColor">= </font>弓箭手</span>',
    m142: '<span class="PrimaryText">机工士</span>',
    m127: '大地使者 / 能工巧匠',
    m143: '<span class="PrimaryText">大地使者</span><br><span class="SecondaryText"><font class="rdColor">= </font>3种</span>',
    m144: '<span class="PrimaryText">能工巧匠</span><br><span class="SecondaryText"><font class="rdColor">= </font>8种</span>',
    m128: '其他',
    m145: '<span class="PrimaryText">极限技</span><br><span class="SecondaryText"><font class="rdColor">= </font>Limit Break</span>',
    m169: '<span class="PrimaryText">宠物数据</span><br><span class="SecondaryText"><font class="rdColor">= </font>不透明度 50%<br><font class="rdColor">= </font>显示在图表中</span>',
    m146: '<span class="PrimaryText">陆行鸟</span><br><span class="SecondaryText"><font class="rdColor">= </font>搭档</span>',
    m220: '<span class="PrimaryText">背景颜色</span><br><span class="SecondaryText"><font class="rdColor">= </font>图表背景颜色</span>',
    m223: '<span class="PrimaryText">分割线颜色</span><br><span class="SecondaryText"><font class="rdColor">= </font>激活“绘制分割线”</span>',
    m224: '分割线不透明度',
    m32: '玩家信息',
    m33: '战斗',
    m34: '承伤',
    m35: '治疗',
    m36: '其他',
    m37: '输出的排名信息',
    m214: '玩家名称',
    m38: '玩家职业和特职图标',
    m39: '攻击持续时间<br><font class="rdColor">= </font>单人攻击总时长',
    m40: '每秒平均伤害<br><font class="rdColor">= </font>基于个人攻击持续时间',
    m41: '战斗持续时间<br><font class="rdColor">= </font>团队战斗总时长',
    m42: '每秒平均伤害<br><font class="rdColor">= </font>基于团队战斗持续时间，更常用。',
    m43: '10秒内平均DPS',
    m44: '30秒内平均DPS',
    m45: '60秒内平均DPS',
    m46: '180秒内平均DPS',
    m47: '该数值为本次战斗中输出伤害在全队的比例',
    m48: '总伤害',
    m49: '攻击次数比例',
    m50: '尝试攻击次数<br><font class="rdColor">= </font>包括自动攻击、技能和未造成伤害的技能。',
    m51: '攻击命中次数<br><font class="rdColor">= </font>仅包括造成有效伤害的攻击。',
    m52: 'Miss攻击次数',
    m53: '任何非Miss的失败攻击<br><font class="rdColor">= </font>包括抵抗、反弹、格挡和闪避等。',
    m54: '暴击次数',
    m55: '暴击率',
    m56: '单次最高伤害',
    m57: '总承受伤害量',
    m58: '总接受治疗量',
    m59: '招架率',
    m60: '格挡率',
    m61: '每秒平均治疗<br><font class="rdColor">= </font>基于团队战斗持续时间',
    m62: '该数值为本次战斗中治疗量在全队的比例',
    m63: '总治疗量',
    m64: '排除过量和伤害吸收的总治疗量',
    m65: '伤害吸收技能的总吸收量<br><font class="rdColor">= </font>鼓舞、黑夜领域等。（取消勾选游戏解析设置中“禁用伤害吸收盾预估”才有效）',
    m66: '过量治疗量',
    m67: '过量治疗百分比',
    m68: '治疗次数<br><font class="rdColor">= </font>包括魔法和能力',
    m69: '治疗暴击次数',
    m70: '治疗暴击率',
    m71: '单次最高治疗量',
    m72: '战斗驱散次数<br><font class="rdColor">= </font>康复',
    m73: '战斗中生命汲取量<br><font class="rdColor">= </font>浴血等',
    m74: '战斗中MP回复量<br><font class="rdColor">= </font>以太超流等',
    m75: '阵亡次数',
    m76: '直击次数<br><font class="rdColor">= </font>4.0新增',
    m77: '直击率<br><font class="rdColor">= </font>4.0新增',
    m78: '直击暴击同时发生次数<br><font class="rdColor">= </font>4.0新增',
    m79: '直击暴击同时发生几率<br><font class="rdColor">= </font>4.0新增',

};
mpCT = {
    m0: 'MopiMopi Overlay',
    m1: '請開始戰鬥。',
    m7: '歷史記錄<i class="material-icons left" style="color: rgba(255,255,255,0.5)">history</i>',
    m3: '隱藏真實ID<i class="material-icons left" style="color: rgba(255,255,255,0.5)">visibility_off</i>',
    m2: 'Healer專屬圖表<i class="material-icons left" style="color: rgba(255,255,255,0.5)">local_hospital</i>',
    m6: '全屏模式<i class="material-icons left" style="color: rgba(255,255,255,0.5)">fullscreen</i>',
    m5: '設置<i class="material-icons left" style="color: rgba(255,255,255,0.5)">settings</i>',
    m10: '設置',
    m20: '自訂',
    m11: '基礎資料內容',
    m30: '選擇需要的資料來定制屬於自己的圖表。',
    m12: 'Healer資料內容',
    m31: '當“Healer專屬圖表”選中時，你可以定制治療職業專屬的資料圖表。',
    m21: '資料處理',
    m80: '合併召喚獸資料',
    m81: '在資料圖表中合併召喚獸和主人的資料。<br><font class="rdColor">= </font>對應召喚師、機工士、學者的寶寶',
    m170: '在使用者圖表中顯示寵物圖表',
    m171: '在使用者圖表中顯示寵物的傷害或治療比例。<br><font class="rdColor">= </font>需先啟動“合併召喚獸資料”',
    m82: '數據數數值型別',
    m83: '<font class="rdColor">OFF </font>整數<font class="rdColor">　　ON </font>小數',
    m84: '千分符',
    m85: '<font class="rdColor">OFF </font>1234<font class="rdColor">　　ON </font>1,234',
    m207: '名稱顯示類型',
    m208: '全名',
    m209: '縮短姓氏',
    m210: '縮短名字',
    m211: '首字母',
    m212: '顯示排名',
    m213: '<font class="rdColor">OFF </font>YOU<font class="rdColor">　　ON </font>1. YOU',
    m215: '姓名',
    m225: '全域功能',
    m226: '設定資料圖表中數位和字元的資料類型。',
    m227: '使用歐洲數位記號',
    m228: '改變小數點(.)和逗號(,)。',
    m229: '使用簡短技能名',
    m230: '<font class="rdColor">OFF </font>紛亂雪月花<font class="rdColor">　　ON </font>雪月花',
    m233: '自動隱藏資料圖表',
    m234: '戰鬥結束指定時間後自動隱藏圖表。',
    m235: '其他設置',
    m236: '更改其他設置項。<br><font class="rdColor">= </font>模版、資料圖表等。',
    m237: '模版大小調整箭頭',
    m238: '<font class="rdColor">OFF </font>隱藏<font class="rdColor">　　ON </font>顯示',
    m239: '資料圖表',
    m240: '功能表按鈕提示',
    m241: '提醒消息',
    m242: '<span class="PrimaryText">自動隱藏等待時間</span><br><span class="SecondaryText"><font class="rdColor">= </font>單位：分鐘</span>',
    m243: '備份',
    m244: '你可以備份和恢復UI設置，或者分享給其他人。',
    m245: '<span>上次備份時間<font id="backupDate" class="rdColor"></font></span>',
    m246: '恢復',
    m247: '從現有資料中恢復設置。',
    m248: '我的數據',
    m249: '匯出設置',
    m250: '導入設置',
    m251: '複製下面的內容（Ctrl+C），不包含某些特定選項。',
    m252: '在下面粘貼之前的備份內容，然後按回車鍵。',
    m253: '備份和恢復',
    m254: '沒有資料，請點擊“備份”來儲存資料。',
    m255: '您真的要恢復嗎？',
    m256: '索引',
    m257: '資料輸出順序',
    m258: '更改資料圖表中每種資料的先後順序',
    m259: '我的角色名字',
    m260: '<font class="rdColor">OFF </font>YOU<font class="rdColor">　　ON </font>神奇的海螺',
    m261: '簡短技能名管理',
    m262: '你可以註冊或者刪除自訂簡短技能名。',
    m263: '<br>PC用戶：在記事本中輸入資料並複製（Ctrl + C），然後粘貼（Ctrl + V）進來。',
    m264: '新增',
    m265: '技能名',
    m266: '縮寫',
    m267: '現有縮寫',
    m268: '提交',
    m269: '對齊格式',
    m270: '<font class="rdColor">OFF </font>關閉<font class="rdColor">　　ON </font>左',
    m22: '顯示',
    m13: '語言',
    m14: '字體',
    m184: '更改字體屬性。<br><font class="rdColor">= </font>字體、大小、顏色、樣式',
    m19: '巡覽列',
    m86: '設計巡覽列來體現獨到品味。',
    m23: '圖表',
    m87: '更改圖表屬性。<br><font class="rdColor">= </font>顏色、效果、不透明度',
    m16: '單元寬度',
    m91: '更改組單元寬度。',
    m24: '版本和開發者資訊',
    m150: '版本',
    m152: '聯繫我們',
    m153: 'ffxivHAERU@gmail.com',
    m200: '關於開發者',
    m201: 'Thanks to :)',
    m25: '還原',
    m26: '管理工具',
    m162: '使用該功能將所有選項恢復為預設設定。',
    m163: '所有的自訂設定會被重置，您的現有統計資料都將被刪除。仍要繼續初始化嗎？',
    m167: '刷新',
    m168: '當模版功能異常時使用。<br>歷史記錄將被清除。',
    m90: '使用PC中安裝好的其他字體<Br><font class="rdColor">= </font>僅限PC使用',
    m102: '進行設置前務必：',
    m103: 'ACT > 插件列表 > 美化模版管理器 > 呼出管理器 > Preference >勾选“No Focus”',
    m101: '<br>1. 你必須輸入字體名稱（字體樣式除外）<br>2. 如果字體檔異常，將會使用默認設置。<br>3. 該功能不支援移動設備。<br>4. PC用戶：輸入中文時，在記事本中輸入資料，複製（Ctrl + C）並粘貼（Ctrl + V）進來。',
    m96: '時間 (00:00)',
    m97: '總體',
    m98: '韓文',
    m275: '簡體中文',
    m276: '正體中文',
    m99: '日語',
    m104: '英文',
    m105: '德文',
    m176: '字號',
    m177: '<span class="PrimaryText">字型大小<br><span class="SecondaryText"><font class="rdColor">= </font>8px ~ 32px</span></span>',
    m129: '顏色',
    m147: '<span class="PrimaryText">用戶<br><span class="SecondaryText"><font class="rdColor">= </font>YOU</span></span>',
    m148: '<span class="PrimaryText">其他人<br><span class="SecondaryText"><font class="rdColor">= </font>小隊成員</span></span>',
    m186: '加粗使用者字元',
    m187: '將表中使用者資料加粗。',
    m188: '加粗他人字元',
    m189: '將表中他人數據加粗。',
    m183: '<span class="PrimaryText">高度</span><br><span class="SecondaryText"><font class="rdColor">= </font>每次更改增加或減少2個單位</span>',
    m100: '預覽',
    m190: '<span class="PrimaryText">背景色 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>巡覽列</span>',
    m172: '<span class="PrimaryText">強調色</span><br><span class="SecondaryText"><font class="rdColor">= </font>時間 (00:00), 圖示</span>',
    m199: '<span class="PrimaryText">描邊顏色</span><br><span class="SecondaryText"><font class="rdColor">= </font>巡覽列</span>',
    m191: '<span class="PrimaryText">文本顏色 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>巡覽列<br><font class="rdColor">= </font>目標名稱</span>',
    m192: '<span class="PrimaryText">文本顏色 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>巡覽列<br><font class="rdColor">= </font>RDPS, RHPS</span>',
    m219: '<span class="PrimaryText">背景顏色 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>表頭</span>',
    m222: '<span class="PrimaryText">文本顏色 3</span><br><span class="SecondaryText"><font class="rdColor">= </font>表頭</span>',
    m221: '表頭不透明度',
    m194: '圓角',
    m195: '將巡覽列邊緣設置為圓角',
    m197: '邊緣繪製',
    m198: '為巡覽列添加1圖元寬度的描邊。',
    m181: '不透明度',
    m193: '巡覽列不透明度',
    m17: '圖表顏色',
    m119: '更換圖表顏色',
    m88: '繪製分割線',
    m89: '在圖表之間繪製分割線。',
    m120: '漸變效果',
    m121: '為圖表添加漸變效果',
    m122: '使用動態過渡效果',
    m123: 'DPS, HPS數值改變時平滑過渡。',
    m15: '背景不透明度',
    m18: '圖表不透明度',
    m204: '效果',
    m217: '啟動Raid模式',
    m218: '戰鬥人數超過九名時簡化顯示。',
    m109: '狹窄單元',
    m111: '狹窄單元1',
    m112: '數值偶爾變化的單元<br><font class="rdColor">= </font>職業, 輸出比例, 死亡次數等等',
    m113: '狹窄單元2',
    m114: 'DPS, HPS單元',
    m110: '寬廣單元',
    m115: '寬廣單元1',
    m116: '數值頻繁變化的單元<br><font class="rdColor">= </font>傷害、治療量等',
    m117: '寬廣單元2',
    m118: 'MaxHit, MaxHeal 單元',
    m154: 'MopiMopi模版皮膚',
    m155: 'Korea [Moogle] Haeru<br>GitHub <font class="rdColor">= </font>HAERUHAERU',
    m160: 'ACT 核心庫：Chamsucript (js/core.js)',
    m161: 'Korea [Moogle] Laiglinne<Br>Elemental [Alexander] Lulala Lula<br>GitHub <font class="rdColor">= </font>laiglinne-ff',
    m156: '日語當地語系化',
    m157: 'Korea [Moogle] Ikaruga',
    m271: '德語當地語系化',
    m272: 'Chaos [Phoenix] Shunittseru Tohka',
    m273: '中文當地語系化/優化',
    m274: '中國區 [紫水棧橋] 幽兒希卡',
    m158: 'ACT WebSocket外掛程式',
    m159: 'Korea [Carbuncle] CoolnyamCoolnyam<br>GitHub <font class="rdColor">= </font>ZCube',
    m205: '應用一個用戶顏色',
    m206: '使用用戶指定的顏色，而非職業顏色',
    m124: '坦克',
    m9: '顏色代碼',
    m130: '<span class="PrimaryText">騎士</span><br><span class="SecondaryText"><font class="rdColor">= </font>劍術師</span>',
    m131: '<span class="PrimaryText">戰士</span><br><span class="SecondaryText"><font class="rdColor">= </font>斧術師</span>',
    m132: '<span class="PrimaryText">暗黑騎士</span>',
    m125: '治療',
    m133: '<span class="PrimaryText">白魔法師</span><br><span class="SecondaryText"><font class="rdColor">= </font>幻術師</span>',
    m134: '<span class="PrimaryText">學者</span>',
    m135: '<span class="PrimaryText">占星術士</span>',
    m165: '<span class="PrimaryText">傷害吸收盾</span><br><span class="SecondaryText"><font class="rdColor">= </font>Healer數據</span>',
    m166: '<span class="PrimaryText">過量治療</span><br><span class="SecondaryText"><font class="rdColor">= </font>Healer資料</span>',
    m126: '輸出',
    m136: '<span class="PrimaryText">武僧</span><br><span class="SecondaryText"><font class="rdColor">= </font>格鬥家</span>',
    m137: '<span class="PrimaryText">龍騎士</span><br><span class="SecondaryText"><font class="rdColor">= </font>槍術師</span>',
    m138: '<span class="PrimaryText">忍者</span><br><span class="SecondaryText"><font class="rdColor">= </font>雙劍師</span>',
    m231: '<span class="PrimaryText">武士</span>',
    m139: '<span class="PrimaryText">黑魔法師</span><br><span class="SecondaryText"><font class="rdColor">= </font>咒術師</span>',
    m140: '<span class="PrimaryText">召喚師</span><br><span class="SecondaryText"><font class="rdColor">= </font>秘術師</span>',
    m232: '<span class="PrimaryText">赤魔法師</span>',
    m141: '<span class="PrimaryText">吟游詩人</span><br><span class="SecondaryText"><font class="rdColor">= </font>弓箭手</span>',
    m142: '<span class="PrimaryText">機工士</span>',
    m127: '大地使者 / 能工巧匠',
    m143: '<span class="PrimaryText">大地使者</span><br><span class="SecondaryText"><font class="rdColor">= </font>3種</span>',
    m144: '<span class="PrimaryText">能工巧匠</span><br><span class="SecondaryText"><font class="rdColor">= </font>8種</span>',
    m128: '其他',
    m145: '<span class="PrimaryText">極限技</span><br><span class="SecondaryText"><font class="rdColor">= </font>Limit Break</span>',
    m169: '<span class="PrimaryText">寵物數據</span><br><span class="SecondaryText"><font class="rdColor">= </font>不透明度 50%<br><font class="rdColor">= </font>顯示在圖表中</span>',
    m146: '<span class="PrimaryText">陸行鳥</span><br><span class="SecondaryText"><font class="rdColor">= </font>搭檔</span>',
    m220: '<span class="PrimaryText">背景顏色</span><br><span class="SecondaryText"><font class="rdColor">= </font>圖表背景顏色</span>',
    m223: '<span class="PrimaryText">分割線顏色</span><br><span class="SecondaryText"><font class="rdColor">= </font>啟動“繪製分割線”</span>',
    m224: '分割線不透明度',
    m32: '玩家信息',
    m33: '戰鬥',
    m34: '承傷',
    m35: '治療',
    m36: '其他',
    m37: '輸出的排名資訊',
    m214: '玩家名稱',
    m38: '玩家職業和特職圖示',
    m39: '攻擊持續時間<br><font class="rdColor">= </font>單人攻擊總時長',
    m40: '每秒平均傷害<br><font class="rdColor">= </font>基於個人攻擊持續時間',
    m41: '戰鬥持續時間<br><font class="rdColor">= </font>團隊戰鬥總時長',
    m42: '每秒平均傷害<br><font class="rdColor">= </font>基於團隊戰鬥持續時間，更常用。',
    m43: '10秒內平均DPS',
    m44: '30秒內平均DPS',
    m45: '60秒內平均DPS',
    m46: '180秒內平均DPS',
    m47: '該數值為本次戰鬥中輸出傷害在全隊的比例',
    m48: '總傷害',
    m49: '攻擊次數比例',
    m50: '嘗試攻擊次數<br><font class="rdColor">= </font>包括自動攻擊、技能和未造成傷害的技能。',
    m51: '攻擊命中次數<br><font class="rdColor">= </font>僅包括造成有效傷害的攻擊。',
    m52: 'Miss攻擊次數',
    m53: '任何非Miss的失敗攻擊<br><font class="rdColor">= </font>包括抵抗、反彈、格擋和閃避等。',
    m54: '暴擊次數',
    m55: '暴擊率',
    m56: '單次最高傷害',
    m57: '總承受傷害量',
    m58: '總接受治療量',
    m59: '招架率',
    m60: '格擋率',
    m61: '每秒平均治療<br><font class="rdColor">= </font>基於團隊戰鬥持續時間',
    m62: '該數值為本次戰鬥中治療量在全隊的比例',
    m63: '總治療量',
    m64: '排除過量和傷害吸收的總治療量',
    m65: '傷害吸收技能的總吸收量<br><font class="rdColor">= </font>鼓舞、黑夜領域等。（取消勾選遊戲解析設置中“禁用傷害吸收盾預估”才有效）',
    m66: '過量治療量',
    m67: '過量治療百分比',
    m68: '治療次數<br><font class="rdColor">= </font>包括魔法和能力',
    m69: '治療暴擊次數',
    m70: '治療暴擊率',
    m71: '單次最高治療量',
    m72: '戰鬥驅散次數<br><font class="rdColor">= </font>康復',
    m73: '戰鬥中生命汲取量<br><font class="rdColor">= </font>浴血等',
    m74: '戰鬥中MP回復量<br><font class="rdColor">= </font>乙太超流等',
    m75: '陣亡次數',
    m76: '直擊次數<br><font class="rdColor">= </font>4.0新增',
    m77: '直擊率<br><font class="rdColor">= </font>4.0新增',
    m78: '直擊暴擊同時發生次數<br><font class="rdColor">= </font>4.0新增',
    m79: '直擊暴擊同時發生幾率<br><font class="rdColor">= </font>4.0新增',
};
mpJP = {
    m0: 'モピモピオーバーレイ',
    m1: '戦闘を始めてください。',
    m7: '履歴<i class="material-icons left" style="color: rgba(255,255,255,0.5)">history</i>',
    m3: 'キャラの名前を隠す<i class="material-icons left" style="color: rgba(255,255,255,0.5)">visibility_off</i>',
    m2: 'ヒーラーのACTを見る<i class="material-icons left" style="color: rgba(255,255,255,0.5)">local_hospital</i>',
    m6: 'フルスクリーンモード<i class="material-icons left" style="color: rgba(255,255,255,0.5)">fullscreen</i>',
    m5: '設定<i class="material-icons left" style="color: rgba(255,255,255,0.5)">settings</i>',
    m10: '設定',
    m20: 'カスタマイズ',
    m11: 'ACTの基本セッティング',
    m30: '色んな組み合わせで自分だけのACTを作成できます。',
    m12: 'ヒーラーのACT設定',
    m31: '\'ヒーラーのACTを見る\'にチェークを入れると、ヒーラーACTに出力する項目を編集できるようになります。',
    m21: 'データ処理',
    m80: 'ペットのデータを合算する',
    m81: 'オーバーレイ内にプレイヤーとペットのデータを合算します。<br><font class="rdColor">= </font>召喚士、機工士、学者',
    m170: 'プレイヤーのグラフにペットのグラフを表示する',
    m171: 'プレイヤーのグラフにペットのダーメジもしくはヒール量の割合を表紙する<br><font class="rdColor">= </font>ペットのデータを合算する \'ON\'',
    m82: '数字データタイプ',
    m83: '<font class="rdColor">OFF </font>整數<font class="rdColor">　　ON </font>小數',
    m84: '3桁ごとに区切りを表示する',
    m85: '<font class="rdColor">OFF </font>1234<font class="rdColor">　　ON </font>1,234',
    m207: '名前の表示タイプ',
    m208: 'フルネーム',
    m209: '姓のみイニシャル',
    m210: '名のみイニシャル',
    m211: '姓名ともにイニシャル',
    m212: 'ランク (DPS 基準)',
    m213: '<font class="rdColor">OFF </font>YOU<font class="rdColor">　　ON </font>1. YOU',
    m225: 'グローバルサーバ',
    m226: 'Sets the data type of the number or character in overlay.',
    m227: 'Apply European Numeric Notation',
    m228: 'Change the period(.) and commas(,) of the numeric data to each other.',
    m229: 'Abbreviate Action\'s Name',
    m230: '<font class="rdColor">OFF </font>Midare Setsugekka<font class="rdColor">　　ON </font>Midare',
    m233: 'Auto-hide the Data Table',
    m234: 'When the encounter is end, hides the data table after latency time automatically.',
    m235: 'その他の設定',
    m236: 'その他の設定を変更します。<br><font class="rdColor">= </font>オーバーレイ、データテーブルなど',
    m237: 'Overaly Resizing Arrow',
    m238: '<font class="rdColor">OFF </font>Hide<font class="rdColor">　　ON </font>Show',
    m239: 'データテーブル',
    m240: 'Menu Tooltips',
    m241: 'Toast Meassage',
    m242: '<span class="PrimaryText">Latency Time</span><br><span class="SecondaryText"><font class="rdColor">= </font>Unit \'Minute\'</span>',
    m243: 'Backup',
    m244: 'You can backup or restore the UI Settings. Or you share or apply it with other users.',
    m245: '<span>Date and time of last backup<font id="backupDate" class="rdColor"></font></span>',
    m246: 'Restore',
    m247: 'Restore UI settings to previous data.',
    m248: 'My data',
    m249: 'Export the Customizing',
    m250: 'Import the Customizing',
    m251: 'Copy under the values (Ctrl+C). NOT contain some values.',
    m252: 'Paste under the values to apply (Ctrl+V), and then Press the Enter key.',
    m253: 'Backup and Restore',
    m254: 'No data. Please click Backup to save the data.',
    m255: 'Do you really want to restore it?',
    m256: 'Index',
    m257: 'Data Output Order',
    m258: 'Change the order of the columns in data table.',
    m259: 'My Character Name',
    m260: '<font class="rdColor">OFF </font>YOU<font class="rdColor">　　ON </font>ex) Lulala Lula',
    m261: 'Action\'s name Abbreviations Management',
    m262: 'You can register or delete action\'s name abbreviations.',
    m263: '',
    m264: 'Register',
    m265: 'Action\'s name (Important! Spacing)',
    m266: 'Abbreviation',
    m267: 'List',
    m268: 'Submit',
    m269: 'Format Align',
    m270: '<font class="rdColor">OFF </font>Center<font class="rdColor">　　ON </font>Left',
    m22: 'ディスプレー',
    m13: '言語',
    m14: 'フォント',
    m184: 'フォントの属性を変更します。<br><font class="rdColor">= </font>フォント、サイズ、色、スタイル',
    m19: '上段バー',
    m86: '上段バーを好みに合わせて変更します。',
    m23: 'グラフ',
    m87: 'グラフの属性を変更します。<br><font class="rdColor">= </font>色、効果、不透明度',
    m16: 'セルの幅',
    m91: 'セルの幅をグループごとに調整します。',
    m24: 'バージョンと開発者情報',
    m150: 'バージョン情報',
    m152: '問い合わせ',
    m153: 'ffxivHAERU@gmail.com',
    m200: '開発者紹介',
    m201: 'Thanks to :)',
    m25: '初期化',
    m26: '管理ツール',
    m162: '全ての設定を基本値に戻す。',
    m163: '設定のよるすべての変更を基本値に戻し、個人データを削除します。初期化を進行しますか？',
    m167: 'リーロド',
    m168: 'オーバーレイがうまく動作しない時に使用してください。<br>前に作成された履歴を除去します。',
    m90: 'PCに設置されているフォントでテキストを変更します。<br><font class="rdColor">= </font>PCのみ可能',
    m102: '設定する前の注意事項',
    m103: 'キーボード入力の場合は,<br>ACT > Plugins > ACTWebSocket > 오버레이 관리자 > 설정 "키 입력 무시"のチェークを解除してください',
    m101: '1. フォントの名前だけ入力してください。(フォントスタイル除外)<br>2. フォントのファイルが損傷されている、もしくは名前が間違っている場合は基本フォントが適用されます。<br>3. 携帯環境では該当オプションは使用できません。',
    m96: '時間 (00:00)',
    m97: '一般',
    m98: '韓國語',
    m99: '日本語',
    m104: '英語',
    m105: '獨逸語',
    m176: 'サイズ',
    m177: '<span class="PrimaryText">フォントサイズ<br><span class="SecondaryText"><font class="rdColor">= </font>8px ~ 32px</span></span>',
    m129: 'テクストの色',
    m147: '<span class="PrimaryText">自分のキャラクター<br><span class="SecondaryText"><font class="rdColor">= </font>YOU</span></span>',
    m148: '<span class="PrimaryText">他のキャラクター<br><span class="SecondaryText"><font class="rdColor">= </font>パーティーメンバー</span></span>',
    m186: '自キャラのテキストを強調する',
    m187: 'データテーブルで表示される自分のキャラクターのテキストを太字にする。',
    m188: '他キャラのテキストを強調する',
    m189: 'データテーブルで表示される他のキャラクターのテキストを太字にする。',
    m183: '<span class="PrimaryText">高さ</span><br><span class="SecondaryText"><font class="rdColor">= </font>2ずつ調整</span>',
    m100: 'プレビュー',
    m190: '<span class="PrimaryText">背景色 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>メーンの上段バー</span>',
    m172: '<span class="PrimaryText">強調色</span><br><span class="SecondaryText"><font class="rdColor">= </font>時間 (00:00), アイコン</span>',
    m199: '<span class="PrimaryText">枠線の色</span><br><span class="SecondaryText"><font class="rdColor">= </font>メーンの上段バー</span>',
    m191: '<span class="PrimaryText">テキストの色 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>ターゲットの名前</span>',
    m192: '<span class="PrimaryText">テキストの色 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>RDPS, RHPS</span>',
    m219: '<span class="PrimaryText">背景色 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>テーブルヘッダ</span>',
    m222: '<span class="PrimaryText">テキストの色 3</span><br><span class="SecondaryText"><font class="rdColor">= </font>テーブルヘッダ</span>',
    m221: 'ヘッダ不透明度',
    m194: '角を丸くする',
    m195: 'メイン上段バーの右と左の上段角に角丸を適用します。',
    m197: '枠線描き',
    m198: 'メイン上段バーに1pxの線を引きます。',
    m181: '不透明度',
    m193: '上段バーの不透明度',
    m17: 'グラフの色',
    m119: 'グラフの色を変更します。',
    m88: '区分線を表示する',
    m89: 'グラフの間に区切り線を表示します。',
    m120: 'グラデーション効果を使用する',
    m121: 'グラフにグラデーション効果を適用します。',
    m122: 'アニメーション変換効果を使用する',
    m123: 'DPS及びHPS変動時グラフをより滑らかに表示します。',
    m15: '背景の不透明度',
    m18: 'グラフ不透明度',
    m204: '効果',
    m217: 'Active the Raid Mode',
    m218: 'If the number of combatants exceeds nine people, the data table displays briefly.',
    m109: '狭いセル',
    m111: '狭いセル 1',
    m112: '変動値が低いセル<br><font class="rdColor">= </font>Job, D%, Deathなど',
    m113: '狭いセル 2',
    m114: 'DPS, HPS',
    m110: '広いセル',
    m115: '広いセル 1',
    m116: '変動値が高いセル<br><font class="rdColor">= </font>Damage, Healedなど',
    m117: '広いセル 2',
    m118: 'MaxHit, MaxHeal',
    m154: 'モピモピオーバーレイスキン',
    m155: 'Korea [Moogle] Haeru<br>GitHub <font class="rdColor">= </font>HAERUHAERU',
    m160: 'ACT コア ライブラリ : Chamsucript (js/core.js)',
    m161: 'Korea [Moogle] Laiglinne<Br>Elemental [Alexander] Lulala Lula<br>GitHub <font class="rdColor">= </font>laiglinne-ff',
    m156: '翻訳 (日本語)',
    m157: 'Korea [Moogle] Ikaruga',
    m271: '翻訳 (獨逸語)',
    m272: 'Chaos [Phoenix] Shunittseru Tohka',
    m273: '翻訳 (中国語)/最適化',
    m274: '中国 [紫水栈桥] 幽兒希卡',
    m158: 'ACT ウェブソケット オーバーレイ フラグイン',
    m159: 'Korea [Carbuncle] CoolnyamCoolnyam<br>GitHub <font class="rdColor">= </font>ZCube',
    m205: 'Applies a User Color',
    m206: 'Applies the user\'s graph in a color you choose regardless of class or job.',
    m9: '色コード',
    m124: 'タンク',
    m130: '<span class="PrimaryText">ナイト</span><br><span class="SecondaryText"><font class="rdColor">= </font>剣術士</span>',
    m131: '<span class="PrimaryText">戦士</span><br><span class="SecondaryText"><font class="rdColor">= </font>斧術士</span>',
    m132: '<span class="PrimaryText">暗黒騎士</span>',
    m125: 'ヒーラー',
    m133: '<span class="PrimaryText">白魔道士</span><br><span class="SecondaryText"><font class="rdColor">= </font>幻術士</span>',
    m134: '<span class="PrimaryText">学者</span>',
    m135: '<span class="PrimaryText">占星術師</span>',
    m165: '<span class="PrimaryText">バリアヒール量</span><br><span class="SecondaryText"><font class="rdColor">= </font>ヒーラーACT</span>',
    m166: '<span class="PrimaryText">オーバーヒール量 </span><br><span class="SecondaryText"><font class="rdColor">= </font>ヒーラーACT</span>',
    m126: 'アタッカー',
    m136: '<span class="PrimaryText">モンク</span><br><span class="SecondaryText"><font class="rdColor">= </font>格闘士</span>',
    m137: '<span class="PrimaryText">竜騎士</span><br><span class="SecondaryText"><font class="rdColor">= </font>槍術士</span>',
    m138: '<span class="PrimaryText">忍者</span><br><span class="SecondaryText"><font class="rdColor">= </font>双剣士</span>',
    m231: '<span class="PrimaryText">侍</span>',
    m139: '<span class="PrimaryText">黒魔道士</span><br><span class="SecondaryText"><font class="rdColor">= </font>呪術士</span>',
    m140: '<span class="PrimaryText">召喚士</span><br><span class="SecondaryText"><font class="rdColor">= </font>巴術士</span>',
    m232: '<span class="PrimaryText">赤魔道士</span>',
    m141: '<span class="PrimaryText">吟遊詩人</span><br><span class="SecondaryText"><font class="rdColor">= </font>弓術士</span>',
    m142: '<span class="PrimaryText">機工士</span>',
    m127: '採集 / 製作',
    m143: '<span class="PrimaryText">採集</span><br><span class="SecondaryText"><font class="rdColor">= </font>3種</span>',
    m144: '<span class="PrimaryText">製作</span><br><span class="SecondaryText"><font class="rdColor">= </font>8種</span>',
    m128: 'その他',
    m145: '<span class="PrimaryText">リミットブレイク</span><br><span class="SecondaryText"><font class="rdColor">= </font>Limit Break</span>',
    m169: '<span class="PrimaryText">ペットのデータ</span><br><span class="SecondaryText"><font class="rdColor">= </font>不透明度 50%<br><font class="rdColor">= </font>ユーザーグラフの上</span>',
    m146: '<span class="PrimaryText">チョコボ</span><br><span class="SecondaryText"><font class="rdColor">= </font>バディ</span>',
    m220: '<span class="PrimaryText">背景色</span><br><span class="SecondaryText"><font class="rdColor">= </font>グラフ背景</span>',
    m223: '<span class="PrimaryText">区分線の色</span><br><span class="SecondaryText"><font class="rdColor">= </font>区分線を表示する \'ON\'</span>',
    m224: '区分線の不透明度',
    m32: 'プレイヤー情報',
    m33: '戦闘項目',
    m34: '被害項目',
    m35: '回復項目',
    m36: 'その他',
    m37: '順位とキャラ名',
    m214: 'キャラ名',
    m38: 'クラスもしくはジョブアイコン',
    m39: '戦闘ログ収集時間<br><font class="rdColor">= </font>自らの攻撃した時点',
    m40: '1秒あたりのダメージ<br><font class="rdColor">= </font>P.Time 時点',
    m41: '戦闘ログ収集時間<br><font class="rdColor">= </font>パティー初めて攻撃した時点',
    m42: '1秒あたりのダメージ<br><font class="rdColor">= </font>Time 時点、オフィシャル',
    m43: '最近10秒間の平均DPS',
    m44: '最近30秒間の平均DPS',
    m45: '最近60秒間の平均DPS',
    m46: '最近180秒間の平均DPS',
    m47: '総ダメージ中自分が与えたダメージ量 (%)',
    m48: 'ダメージ量',
    m49: '命中率 (%)',
    m50: '攻撃回数<br><font class="rdColor">= </font>オートアタック、DOT、スキルキャンセル含め',
    m51: '攻撃の命中回数',
    m52: '攻撃のミス回数',
    m53: '攻撃の失敗回数<br><font class="rdColor">= </font>敵の抵抗、反射、ブロック、回避など',
    m54: '攻撃のクリティカル回数',
    m55: '攻撃のクリティカル率 (%)',
    m56: '最大ダメージのスキル',
    m57: '受けた被ダメージ量',
    m58: '貰ったヒール量',
    m59: '受け流し発動率 (%)',
    m60: '盾ブロック発動率 (%)',
    m61: '1秒あたりのヒール量<br><font class="rdColor">= </font>Time 時点、オフィシャル',
    m62: '総ヒール量中自分が回復したヒール量 (%)',
    m63: '総ヒール量',
    m64: '有効総ヒール量',
    m65: 'バリアヒール量<br><font class="rdColor">= </font>鼓舞、ノクターナルセクト',
    m66: 'オーバーヒール量',
    m67: 'オーバーヒール率 (%)',
    m68: 'ヒール回数<br><font class="rdColor">= </font>HOT、スキルキャンセル含む',
    m69: '回復のクリティカル回数',
    m70: '回復のクリティカル率 (%)',
    m71: '最大回復のスキル',
    m72: 'デバフ解除スキルの使用回数<br><font class="rdColor">= </font>エスナ',
    m73: 'スキルのよるHP回復量<br><font class="rdColor">= </font>マーシーストロークなど',
    m74: 'スキルのよるMP回復量<br><font class="rdColor">= </font>エーテルフローなど',
    m75: '死亡回数',
    m76: 'Direct Hits 回数',
    m77: 'Direct Hits 発動率 (%)',
    m78: 'Direct Hits クリティカル回数',
    m79: 'Direct Hits クリティカル率 (%)',
    m401: '职业',
};
mpEN = {
    m0: 'MopiMopi Overlay',
    m1: 'Please start the combat.',
    m7: 'History<i class="material-icons left" style="color: rgba(255,255,255,0.5)">history</i>',
    m3: 'Hide the R. Name<i class="material-icons left" style="color: rgba(255,255,255,0.5)">visibility_off</i>',
    m2: 'View Healer ACT<i class="material-icons left" style="color: rgba(255,255,255,0.5)">local_hospital</i>',
    m6: 'Fullscreen Mode<i class="material-icons left" style="color: rgba(255,255,255,0.5)">fullscreen</i>',
    m5: 'Settings<i class="material-icons left" style="color: rgba(255,255,255,0.5)">settings</i>',
    m10: 'Settings',
    m20: 'Customizing',
    m11: 'Basic ACT Fomatting',
    m30: 'You can create my own ACT by selecting the multiple items.',
    m12: 'Healer ACT Formatting',
    m31: 'You can select the items to output on Healer ACT when \'View Healer ACT\' is checked.',
    m21: 'Data Processing',
    m80: 'Combine Pets with Owner',
    m81: 'Combine the pet\'s data with the owner\'s data within the overlay.<br><font class="rdColor">= </font>SMN, MCH, SCH',
    m170: 'Display Pet\'s Graph on User Graph',
    m171: 'Displays the percentage of pet\'s Damage or Healed on the user graph.<br><font class="rdColor">= </font>Combine Pets with Owner \'Checked\'',
    m82: 'Number Data Type',
    m83: '<font class="rdColor">OFF </font>Integer<font class="rdColor">　　ON </font>Decimal',
    m84: 'Thousand Separators',
    m85: '<font class="rdColor">OFF </font>1234<font class="rdColor">　　ON </font>1,234',
    m207: 'Name Display Type',
    m208: 'Full Name',
    m209: 'Surname Abbreviated',
    m210: 'Forename Abbreviated',
    m211: 'Initials',
    m212: 'Ranking (Sort by DPS)',
    m213: '<font class="rdColor">OFF </font>YOU<font class="rdColor">　　ON </font>1. YOU',
    m225: 'Global Server',
    m226: 'Sets the data type of the number or character in overlay.',
    m227: 'Apply European Numeric Notation',
    m228: 'Change the period(.) and commas(,) of the numeric data to each other.',
    m229: 'Abbreviate Action\'s Name',
    m230: '<font class="rdColor">OFF </font>Midare Setsugekka<font class="rdColor">　　ON </font>Midare',
    m233: 'Auto-hide the Data Table',
    m234: 'When the encounter is end, hides the data table after latency time automatically.',
    m235: 'Other Settings',
    m236: 'Change the properties of other settings.<br><font class="rdColor">= </font>Overlay, Data Table etc.',
    m237: 'Overaly Resizing Arrow',
    m238: '<font class="rdColor">OFF </font>Hide<font class="rdColor">　　ON </font>Show',
    m239: 'Data Table',
    m240: 'Menu Tooltips',
    m241: 'Toast Meassage',
    m242: '<span class="PrimaryText">Latency Time</span><br><span class="SecondaryText"><font class="rdColor">= </font>Unit \'Minute\'</span>',
    m243: 'Backup',
    m244: 'You can backup or restore the UI Settings. Or you share or apply it with other users.',
    m245: '<span>Date and time of last backup<font id="backupDate" class="rdColor"></font></span>',
    m246: 'Restore',
    m247: 'Restore UI settings to previous data.',
    m248: 'My data',
    m249: 'Export the Customizing',
    m250: 'Import the Customizing',
    m251: 'Copy under the values (Ctrl+C). NOT contain some values.',
    m252: 'Paste under the values to apply (Ctrl+V), and then Press the Enter key.',
    m253: 'Backup and Restore',
    m254: 'No data. Please click Backup to save the data.',
    m255: 'Do you really want to restore it?',
    m256: 'Index',
    m257: 'Data Output Order',
    m258: 'Change the order of the columns in data table.',
    m259: 'My Character Name',
    m260: '<font class="rdColor">OFF </font>YOU<font class="rdColor">　　ON </font>ex) Lulala Lula',
    m261: 'Action\'s name Abbreviations Management',
    m262: 'You can register or delete action\'s name abbreviations.',
    m263: '',
    m264: 'Register',
    m265: 'Action\'s name (Important! Spacing)',
    m266: 'Abbreviation',
    m267: 'List',
    m268: 'Submit',
    m269: 'Format Align',
    m270: '<font class="rdColor">OFF </font>Center<font class="rdColor">　　ON </font>Left',
    m22: 'Display',
    m13: 'Language',
    m14: 'Font',
    m184: 'Change the properties of font.<br><font class="rdColor">= </font>Font, Size, Color, Style',
    m19: 'Navigation Bar',
    m86: 'Designs the navigation bar to suit individual tastes.',
    m23: 'Graph',
    m87: 'Change the properties of graph.<br><font class="rdColor">= </font>Color, Effect, Opacity',
    m16: 'Cell Width',
    m91: 'Adjust the width of cells by groups.',
    m24: 'Version and Developer Info',
    m150: 'Version',
    m152: 'Contact Us',
    m153: 'ffxivHAERU@gmail.com',
    m200: 'About the Developer',
    m201: 'Thanks to :)',
    m25: 'Reset',
    m26: 'Management Tools',
    m162: 'You use this option that restore the values for all settings to the default.',
    m163: 'Any changes to the settings will be restored to their defaults and your personal data will be deleted. Do you want to proceed with the initialization?',
    m167: 'Refresh',
    m168: 'You use this option when overlay operation is abnormal.<br>The history will be deleted.',
    m90: 'Change the font installed on your computer.<br><font class="rdColor">= </font>Only PC',
    m102: 'Read before Setting',
    m103: 'When you type directly,<br>ACT > Plugins > ACTWebSocket > Click "Open Manager" > Tab "Preferences" > UNCHEKED "No Focus"',
    m101: '1. You only must be entered the font name. (EXCEPT font style)<br>2. If the font file is corrupted or font name is entered incorrectly, it will be applied by default.<br>3. This feature isn\'t supported in mobile environment.',
    m96: 'Time (00:00)',
    m97: 'General',
    m98: 'Korean',
    m99: 'Japanese',
    m104: 'English',
    m105: 'Deutsch',
    m176: 'Size',
    m177: '<span class="PrimaryText">Size<br><span class="SecondaryText"><font class="rdColor">= </font>8px ~ 32px</span></span>',
    m129: 'Color',
    m147: '<span class="PrimaryText">User<br><span class="SecondaryText"><font class="rdColor">= </font>YOU</span></span>',
    m148: '<span class="PrimaryText">Others<br><span class="SecondaryText"><font class="rdColor">= </font>Party Members</span></span>',
    m186: 'Bold lettring : User',
    m187: 'Applies bold formatting to the text of User in data table.',
    m188: 'Bold lettring : Others',
    m189: 'Applies bold formatting to the text of Others in data table.',
    m183: '<span class="PrimaryText">Height</span><br><span class="SecondaryText"><font class="rdColor">= </font>2 Increase or Decrease</span>',
    m100: 'Preview',
    m190: '<span class="PrimaryText">Background Color 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>Navigation Bar</span>',
    m172: '<span class="PrimaryText">Accent Color</span><br><span class="SecondaryText"><font class="rdColor">= </font>Time (00:00), Icon</span>',
    m199: '<span class="PrimaryText">Border Color</span><br><span class="SecondaryText"><font class="rdColor">= </font>Navigation Bar</span>',
    m191: '<span class="PrimaryText">Text Color 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>Target Name</span>',
    m192: '<span class="PrimaryText">Text Color 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>RDPS, RHPS</span>',
    m219: '<span class="PrimaryText">Background Color 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>Table Header</span>',
    m222: '<span class="PrimaryText">Text Color 3</span><br><span class="SecondaryText"><font class="rdColor">= </font>Table Header</span>',
    m221: 'Header Opacity',
    m194: 'Rounded Corner',
    m195: 'Rounded the left and right upper corners of the navigation bar.',
    m197: 'Draw Border',
    m198: 'An 1px border surrounds the navigation bar.',
    m181: 'Opacity',
    m193: 'Navigation Bar Opacity',
    m17: 'Graph Color',
    m119: 'Change the color of graph.',
    m88: 'Draw Division Lines',
    m89: 'Draw division lines between graphs.',
    m120: 'Fill Graph with Gradient',
    m121: 'Applies a gradient effect to the graph.',
    m122: 'Use Animated Transition Effect',
    m123: 'Shows graph smoothly when the DPS value or the HPS value is changed.',
    m15: 'Background Opacity',
    m18: 'Graph Opacity',
    m204: 'Effect',
    m217: 'Active the Raid Mode',
    m218: 'If the number of combatants exceeds nine people, the data table displays briefly.',
    m109: 'Narrow Cells',
    m111: 'Narrow Cells 1',
    m112: 'Cells with low variability of values.<br><font class="rdColor">= </font>Job, D%, Death etc',
    m113: 'Narrow Cells 2',
    m114: 'DPS, HPS ',
    m110: 'Wide Cells',
    m115: 'Wide Cells 1',
    m116: 'Cells with high variability of values.<br><font class="rdColor">= </font>Damage, Healed etc',
    m117: 'Wide Cells 2',
    m118: 'MaxHit, MaxHeal',
    m154: 'MopiMopi Overlay Skin',
    m155: 'Korea [Moogle] Haeru<br>GitHub <font class="rdColor">= </font>HAERUHAERU',
    m160: 'ACT Core Library : Chamsucript (js/core.js)',
    m161: 'Korea [Moogle] Laiglinne<Br>Elemental [Alexander] Lulala Lula<br>GitHub <font class="rdColor">= </font>laiglinne-ff',
    m156: 'Translation (Japanese)',
    m157: 'Korea [Moogle] Ikaruga',
    m271: 'Translation (Deutsch)',
    m272: 'Chaos [Phoenix] Shunittseru Tohka',
    m273: 'Translation (Chinese)/Optimization',
    m274: 'China [紫水栈桥] 幽兒希卡',
    m158: 'ACT WebSocket Overlay Plugin',
    m159: 'Korea [Carbuncle] CoolnyamCoolnyam<br>GitHub <font class="rdColor">= </font>ZCube',
    m205: 'Applies a User Color',
    m206: 'Applies the user\'s graph in a color you choose regardless of class or job.',
    m124: 'Tanker',
    m9: 'Color Code',
    m130: '<span class="PrimaryText">Paladin</span><br><span class="SecondaryText"><font class="rdColor">= </font>Gladiator</span>',
    m131: '<span class="PrimaryText">Warrior</span><br><span class="SecondaryText"><font class="rdColor">= </font>Marauder</span>',
    m132: '<span class="PrimaryText">Dark Knight</span>',
    m125: 'Healer',
    m133: '<span class="PrimaryText">White Mage</span><br><span class="SecondaryText"><font class="rdColor">= </font>Conjurer</span>',
    m134: '<span class="PrimaryText">Scholar</span>',
    m135: '<span class="PrimaryText">Astrologian</span>',
    m165: '<span class="PrimaryText">D.Shield</span><br><span class="SecondaryText"><font class="rdColor">= </font>Healer ACT</span>',
    m166: '<span class="PrimaryText">Overheal</span><br><span class="SecondaryText"><font class="rdColor">= </font>Healer ACT</span>',
    m126: 'Dealer',
    m136: '<span class="PrimaryText">Monk</span><br><span class="SecondaryText"><font class="rdColor">= </font>Pugilist</span>',
    m137: '<span class="PrimaryText">Dragoon</span><br><span class="SecondaryText"><font class="rdColor">= </font>Lancer</span>',
    m138: '<span class="PrimaryText">Ninja</span><br><span class="SecondaryText"><font class="rdColor">= </font>Rogue</span>',
    m231: '<span class="PrimaryText">Samurai</span>',
    m139: '<span class="PrimaryText">Black Mage</span><br><span class="SecondaryText"><font class="rdColor">= </font>Thaumaturge</span>',
    m140: '<span class="PrimaryText">Summoner</span><br><span class="SecondaryText"><font class="rdColor">= </font>Arcanist</span>',
    m232: '<span class="PrimaryText">Red Mage</span>',
    m141: '<span class="PrimaryText">Bard</span><br><span class="SecondaryText"><font class="rdColor">= </font>Archer</span>',
    m142: '<span class="PrimaryText">Machinist</span>',
    m127: 'Gathering / Crafting',
    m143: '<span class="PrimaryText">Gathering</span><br><span class="SecondaryText"><font class="rdColor">= </font>3 Kinds</span>',
    m144: '<span class="PrimaryText">Crafting</span><br><span class="SecondaryText"><font class="rdColor">= </font>8 Kinds</span>',
    m128: 'Other',
    m145: '<span class="PrimaryText">Limit Break</span>',
    m169: '<span class="PrimaryText">Pets Data</span><br><span class="SecondaryText"><font class="rdColor">= </font>Opacity 50%<br><font class="rdColor">= </font>on the User Graph</span>',
    m146: '<span class="PrimaryText">Chocobo</span><br><span class="SecondaryText"><font class="rdColor">= </font>Buddy</span>',
    m220: '<span class="PrimaryText">Background Color</span><br><span class="SecondaryText"><font class="rdColor">= </font>Graph Background</span>',
    m223: '<span class="PrimaryText">Division Lines Color</span><br><span class="SecondaryText"><font class="rdColor">= </font>Draw Division Lines \'ON\'</span>',
    m224: 'Division Lines Opacity',
    m32: 'Player\'s Info',
    m33: 'Combat',
    m34: 'Tanking',
    m35: 'Healing',
    m36: 'Etc',
    m37: 'The combatant\'s rank and name.',
    m214: 'The combatant\'s name.',
    m38: 'Player\'s class or job icon.',
    m39: 'The duration of the combatant.',
    m40: 'The damage total of the combatant divided by their personal duration.',
    m41: 'The duration of the encounter.',
    m42: 'The damage total of the combatant divided by the duration of the encounter.<br><font class="rdColor">= </font>This is more commonly used than P.DPS',
    m43: 'Average DPS for last 10 seconds.',
    m44: 'Average DPS for last 30 seconds.',
    m45: 'Average DPS for last 60 seconds.',
    m46: 'Average DPS for last 180 seconds.',
    m47: 'This value represents the percent share of all damage done by allies in this encounter.',
    m48: 'The amount of damage.',
    m49: 'The percentage of hits to swings.',
    m50: 'The number of attack attempts.<br><font class="rdColor">= </font>This includes any auto-attacks or abilities, also including resisted abilities that do no damage.',
    m51: 'The number of attack attempts that produced damage.',
    m52: 'The number of auto-attacks of CAs that produced a miss message.',
    m53: 'Any type of failed attack that was not a miss.<br><font class="rdColor">= </font>This includes resists, reflects, blocks, dodging, etc.',
    m54: 'The number of damaging attacks that were critical.',
    m55: 'The percentage of damaging attacks that were critical.',
    m56: 'The highest single damaging hit.',
    m57: 'The amount of damage this combatant received.',
    m58: 'The amount of healing this combatant received.',
    m59: 'The percentage of hits that were parried.',
    m60: 'The percentage of hits that were blocked.',
    m61: 'The healing total of the combatant divided by the duration of the encounter.',
    m62: 'The value represents the percent share of all healing done by allies in this encounter.',
    m63: 'The amount of healing.',
    m64: 'The amount of healing except for Overheal and D.Shield value.',
    m65: 'The amount of damage blocked by shield abilities of healer.<br><font class="rdColor">= </font>Galvanize effects, Nocturnal Field',
    m66: 'The amount of healing that made flood over 100% of health.',
    m67: 'The percentage of heals above target\'s Max HP.',
    m68: 'The number of heals from this combatant.',
    m69: 'The number of heals that were critical.',
    m70: 'The percentage of heals that were critical.',
    m71: 'The highest single healing amount.',
    m72: 'The number of times the combatant dispelled.<br><font class="rdColor">= </font>Esuna',
    m73: 'The amount of power this combatant drained from others.<br><font class="rdColor">= </font>ex. Mercy Stroke etc',
    m74: 'The amount of power this combatant replenished to others.<br><font class="rdColor">= </font>ex. Aetherflow etc',
    m75: 'The number of times this character was killed by another.',
    m76: 'The number of hits that were direct hit.',
    m77: 'The percentage of hits that were direct hits.',
    m78: 'The number of hits that were critical as well as direct hit.',
    m79: 'The percentage of hits that were direct hits as well as critical hits.',
};
mpDE = {
    m0: 'MopiMopi Overlay',
    m1: 'Warte auf Kampf.',
    m7: 'Historie<i class="material-icons left" style="color: rgba(255,255,255,0.5)">history</i>',
    m3: 'Namen ausblenden<i class="material-icons left" style="color: rgba(255,255,255,0.5)">visibility_off</i>',
    m2: 'Heiler ACT anzeigen<i class="material-icons left" style="color: rgba(255,255,255,0.5)">local_hospital</i>',
    m6: 'Vollbild Modus<i class="material-icons left" style="color: rgba(255,255,255,0.5)">fullscreen</i>',
    m5: 'Einstellungen<i class="material-icons left" style="color: rgba(255,255,255,0.5)">settings</i>',
    m10: 'Einstellungen',
    m20: 'Allgemein',
    m11: 'DPS Werte',
    m30: 'Wähle hier die Werte aus, die angezeigt werden sollen.',
    m12: 'Heiler Werte',
    m31: 'Wähle die Werte aus, die angezeigt werden wenn \'Heiler ACT anzeigen\' aktiviert ist.',
    m21: 'Anzeigeeinstellungen',
    m80: 'Charakter und Begleiter zusammenfassen',
    m81: 'Fasse die Werte des Charakters und dessen Begleiter zusammen<br><font class="rdColor">= </font>SMN, MCH, SCH',
    m170: 'Kombinierte Graphen',
    m171: 'Zeigt prozentual den Schaden oder die Heilung des Begleiters im Graph des Charakters an<br><font class="rdColor">Vorraussetzung = </font>  \'Charakter und Begleiter zusammenfassen\' aktiviert',
    m82: 'Datentyp der Zahlen',
    m83: '<font class="rdColor">OFF </font>Integer<font class="rdColor">　　ON </font>Dezimal',
    m84: 'Tausender Trennzeichen',
    m85: '<font class="rdColor">OFF </font>1234<font class="rdColor">　　ON </font>1,234',
    m207: 'Anzeigetyp des Namens',
    m208: 'Voller Name',
    m209: 'Nachname abgekürzt',
    m210: 'Vorname abgekürzt',
    m211: 'Initialien',
    m212: 'Sortierung',
    m213: '<font class="rdColor">OFF </font>Nach DPS sortiert<font class="rdColor">　　ON </font>1. Platz = DU',
    m225: 'Globale Einstellungen',
    m226: 'Passe die Formatierung der Charakternamen und die Zahlenschreibweise an.',
    m227: 'Nutze Europäische Notation',
    m228: 'Tausche Punkt(.) gegen Komma(,) bei Zahlen (und umgekehrt).',
    m229: 'Abgekürzte Fähigkeitsnamen',
    m230: '<font class="rdColor">OFF </font>Midare Setsugekka<font class="rdColor">　　ON </font>Midare',
    m233: 'Automatisches ausblenden der Daten',
    m234: 'Blendt automaitsch nach einer Verzögerung die Daten aus, sobald der Kampf vorbei ist.',
    m235: 'Weitere Einstellungen',
    m236: 'Passe weitere Einstellungen an.<br><font class="rdColor">= </font>Overlay, Tabelle, usw.',
    m237: 'Pfeil zur Größenveränderung des Fensters',
    m238: '<font class="rdColor">OFF </font>Ausblenden<font class="rdColor">　　ON </font>Anzeigen',
    m239: 'Tabelle - Data Table',
    m240: 'Kurzhinweise im Menü',
    m241: 'Toast-Benachrichtigungen',
    m242: '<span class="PrimaryText">Latenz</span><br><span class="SecondaryText"><font class="rdColor">= </font>Einheit \'Minute\'</span>',
    m243: 'Sicherung',
    m244: 'Erstelle Sicherungen deiner Einstellungen und teile sie mit anderen oder stell die Einstellungen (von anderen) wieder her.',
    m245: '<span>Zeit der letzten Sicherung <font id="backupDate" class="rdColor"></font></span>',
    m246: 'Wiederherstellen',
    m247: 'Stelle die Einstellungen der Benutzeroberfläche wieder her.',
    m248: 'Meine Daten',
    m249: 'Exportiere die Anzeigeeinstellungen',
    m250: 'Importiere die Anzeigeeinstellungen',
    m251: 'Kopiere die unteren Werte (Strg+C). Manche Daten sind nicht enthalten.',
    m252: 'Füge kopierte Werte unten ein (Strg+V) und drücke die Eingabetaste.',
    m253: 'Sichern und Wiederherstellen',
    m254: 'Kein Sicherung vorhanden. Bitte klicke um eine zu erstellen.',
    m255: 'Möchtest du die Einstellungen wirklich wiederherstellen?',
    m256: 'Index',
    m257: 'Reihenfolge der Daten',
    m258: 'Passe die Reihenfolge der Spalten in der Datentabelle an.',
    m259: 'Eigener Charaktername',
    m260: '<font class="rdColor">OFF </font>DU<font class="rdColor">　　ON </font> (z.B.) Shunittseru Tohka',
    m261: 'Einstellungen der Abgekürzten Fähigkeitsnamen.',
    m262: 'Hier kannst du Abkürzungen der Fähigkeiten neu erstellen oder löschen.',
    m263: '',
    m264: 'Register',
    m265: 'Fähigkeitsname (Achte auf Leerzeichen!)',
    m266: 'Abkürzung',
    m267: 'Liste der aktiven Abkürzungen',
    m268: 'Hinzufügen',
    m269: 'Textausrichtung',
    m270: '<font class="rdColor">OFF </font>Zentriert<font class="rdColor">　　ON </font>Linksbündig',
    m22: 'Anzeige',
    m13: 'Sprache',
    m14: 'Schrift',
    m184: 'Ändere die Einstellungen der Schrift.<br><font class="rdColor">= </font>Schriftart, Schriftgröße, Schriftfarbe, Stil',
    m19: 'Navigationsleiste',
    m86: 'Entwerfe ein Design, welches deinen Bedürfnissen gerecht wird.',
    m23: 'Diagramm',
    m87: 'Ändere die Einstellungen des Diagrammes.<br><font class="rdColor">= </font>Farbe, Effekte, Deckkraft',
    m16: 'Zellenbreite',
    m91: 'Passe die Weite der Zellen (gruppiert) an.',
    m24: 'Version und Entwickler Informationen',
    m150: 'Version',
    m152: 'Kontaktiere uns',
    m153: 'ffxivHAERU@gmail.com',
    m200: 'Über die Entwickler',
    m201: 'Overlay, Plugin, Übersetzung',
    m25: 'Zurücksetzen',
    m26: 'Management Tools',
    m162: 'Nutze diese Option um alle Werkseinstellungen wiederherzustellen.',
    m163: 'Alle Einstellungen werden zurück gesetzt. Deine persönlichen Einstellungen gehen unwiderruflich verloren! Möchtest du fortfahren?',
    m167: 'Auffrischen',
    m168: 'Nutze diese Option, falls das Overlay nicht richtig funktioniert.<br>Die Historie wird gelöscht.',
    m90: 'Ändere die Schriftart (muss installiert sein auf dem Computer).<br><font class="rdColor">= </font>Ausschließlich auf diesem PC',
    m102: 'Erst alles genau durchlesen, dann Einstellungen vornehmen!',
    m103: 'Wenn du direkt schreiben möchtest, gehe wie folgt vor:,<br>ACT > Plugins > ACTWebSocket > Klicke auf "Open Manager" > Tab "Preferences" > DEAKTIVIERE "No Focus"',
    m101: '1. Nur den Schriftart-Namen eintragen.(AUSNAHME: Schriftstil)<br>2. Falls die Datei der Schriftart beschädigt oder der Name falsch geschrieben ist, wird die Standard-Schriftart angewendet.<br>3. Dieses Feature wird nicht in der mobilen Umgebung unterstützt.',
    m96: 'Time (00:00)',
    m97: 'Allgemeines',
    m98: 'Koreanisch',
    m99: 'Japanisch',
    m104: 'Englisch',
    m105: 'Deutsch',
    m176: 'Größe',
    m177: '<span class="PrimaryText">Size<br><span class="SecondaryText"><font class="rdColor">= </font>8px ~ 32px</span></span>',
    m129: 'Farbe',
    m147: '<span class="PrimaryText">Nutzer<br><span class="SecondaryText"><font class="rdColor">= </font>DU</span></span>',
    m148: '<span class="PrimaryText">Andere<br><span class="SecondaryText"><font class="rdColor">= </font>Gruppen Mitglieder</span></span>',
    m186: 'Fette Buchstaben: Nutzer',
    m187: 'Formatiert den Text des Nutzers in der Tabelle fett.',
    m188: 'Fette Buchstaben: Andere',
    m189: 'Formatiert den Text der Anderen in der Tabelle fett.',
    m183: '<span class="PrimaryText">Höhe</span><br><span class="SecondaryText"><font class="rdColor">= </font>In zweier Schritten einstellbar</span>',
    m100: 'Vorschau',
    m190: '<span class="PrimaryText">Hintergrund Farbe 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>Navigationsleiste *</span>',
    m172: '<span class="PrimaryText">Farbakzent</span><br><span class="SecondaryText"><font class="rdColor">= </font>Zeit (00:00), Symbole</span>',
    m199: '<span class="PrimaryText">Randfarbe</span><br><span class="SecondaryText"><font class="rdColor">= </font>Navigationsleiste *</span>',
    m191: '<span class="PrimaryText">Textfarbe 1</span><br><span class="SecondaryText"><font class="rdColor">= </font>Name des Ziels</span>',
    m192: '<span class="PrimaryText">Textfarbe 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>RDPS, RHPS</span>',
    m219: '<span class="PrimaryText">Hintergrund Farbe 2</span><br><span class="SecondaryText"><font class="rdColor">= </font>Tabellenkopf *</span>',
    m222: '<span class="PrimaryText">Textfarbe 3</span><br><span class="SecondaryText"><font class="rdColor">= </font>Tabellenkopf *</span>',
    m221: 'Deckkraft Header',
    m194: 'Abgerundete Ecken',
    m195: 'Runde die obere linke sowie rechte Ecke der Navigationsleiste ab.',
    m197: 'Rand anzeigen',
    m198: 'Zeige einen 1px großen Rand an, welcher die Navigationsleiste umgibt.',
    m181: 'Deckkraft',
    m193: 'Deckkraft Navigationsleiste',
    m17: 'Farbe der Graphen',
    m119: 'Ändere die Farben der Graphen.',
    m88: 'Trennlinien anzeigen',
    m89: 'Zeige Trennlinien zwischen den Graphen an.',
    m120: 'Gradient-Effekt',
    m121: 'Abnehmende Deckkraft der Farbe des Graphen',
    m122: 'Weicher, Animierter Übergang',
    m123: 'Graph wird bei Update des DPS/HPS weich animiert.',
    m15: 'Deckkraft Hintergrund',
    m18: 'Deckkraft Graph',
    m204: 'Effekt',
    m217: 'Aktiviere den Raid Modus',
    m218: 'Automatische Anpassung der Graphen, falls die Anzahl der Kämpfer > 9 beträgt.',
    m109: 'Schmale Spalten',
    m111: 'Schmale Spalten 1',
    m112: 'Spalten mit geringer Breite und wenig wechselnden Werten<br><font class="rdColor">= </font>Job, D%, Tote, usw.',
    m113: 'Schmale Spalten 2',
    m114: '<font class="rdColor">= </font>DPS, HPS',
    m110: 'Breite Spalten',
    m115: 'Breite Spalten 1',
    m116: 'Spalten mit erweiterter Breite und stark wechselnden Werten.<br><font class="rdColor">= </font>Schaden, Heilung, usw.',
    m117: 'Breite Spalten 2',
    m118: 'MaxHit, MaxHeal',
    m154: 'MopiMopi Overlay Skin',
    m155: 'Korea [Moogle] Haeru<br>GitHub <font class="rdColor">= </font>HAERUHAERU',
    m160: 'ACT Core Bibliothek : Chamsucript (js/core.js)',
    m161: 'Korea [Moogle] Laiglinne<Br>Elemental [Alexander] Lulala Lula<br>GitHub <font class="rdColor">= </font>laiglinne-ff',
    m156: 'Übersetzung (Japanisch)',
    m157: 'Korea [Moogle] Ikaruga',
    m271: 'Übersetzung (Deutsch)',
    m272: 'Chaos [Phoenix] Shunittseru Tohka',
    m273: 'Übersetzung (Chinesisch)/Optimierung',
    m274: 'China [紫水栈桥] 幽兒希卡',
    m158: 'ACT WebSocket Overlay Plugin',
    m159: 'Korea [Carbuncle] CoolnyamCoolnyam<br>GitHub <font class="rdColor">= </font>ZCube',
    m205: 'Eigene Farbe für eigenen Charakter',
    m206: 'Nutze eine selbst ausgewählte Farbe für den eigenen Charakter. Überschreibt Klassen/Job Farben',
    m124: 'Verteidiger',
    m9: 'Farb Code',
    m130: '<span class="PrimaryText">Paladin</span><br><span class="SecondaryText"><font class="rdColor">= </font>Gladiator</span>',
    m131: '<span class="PrimaryText">Krieger</span><br><span class="SecondaryText"><font class="rdColor">= </font>Marodeur</span>',
    m132: '<span class="PrimaryText">Dunkelritter</span>',
    m125: 'Heiler',
    m133: '<span class="PrimaryText">Weißmagier</span><br><span class="SecondaryText"><font class="rdColor">= </font>Druide</span>',
    m134: '<span class="PrimaryText">Gelehrter</span>',
    m135: '<span class="PrimaryText">Astrologe</span>',
    m165: '<span class="PrimaryText">Schilde</span><br><span class="SecondaryText"><font class="rdColor">= </font>Healer ACT *</span>',
    m166: '<span class="PrimaryText">Overheal</span><br><span class="SecondaryText"><font class="rdColor">= </font>Healer ACT *</span>',
    m126: 'Angreifer',
    m136: '<span class="PrimaryText">Mönch</span><br><span class="SecondaryText"><font class="rdColor">= </font>Faustkämpfer</span>',
    m137: '<span class="PrimaryText">Dragoon</span><br><span class="SecondaryText"><font class="rdColor">= </font>Pikinier</span>',
    m138: '<span class="PrimaryText">Ninja</span><br><span class="SecondaryText"><font class="rdColor">= </font>Schurke</span>',
    m231: '<span class="PrimaryText">Samurai</span>',
    m139: '<span class="PrimaryText">Schwarzmagier</span><br><span class="SecondaryText"><font class="rdColor">= </font>Thaumaturg</span>',
    m140: '<span class="PrimaryText">Beschwörer</span><br><span class="SecondaryText"><font class="rdColor">= </font>Hermetiker</span>',
    m232: '<span class="PrimaryText">Rotmagier</span>',
    m141: '<span class="PrimaryText">Barde</span><br><span class="SecondaryText"><font class="rdColor">= </font>Waldläufer</span>',
    m142: '<span class="PrimaryText">Maschinist</span>',
    m127: 'Sammler und Handwerker',
    m143: '<span class="PrimaryText">Sammler</span><br><span class="SecondaryText"><font class="rdColor">= </font>MIN, FIS, GÄR</span>',
    m144: '<span class="PrimaryText">Handwerker</span><br><span class="SecondaryText"><font class="rdColor">= </font>8 Arten</span>',
    m128: 'Andere',
    m145: '<span class="PrimaryText">Limitrausch</span>',
    m169: '<span class="PrimaryText">Begleiter Daten</span><br><span class="SecondaryText"><font class="rdColor">= </font>Deckkraft 50%<br><font class="rdColor">= </font>auf dem Graph des Charakters *</span>',
    m146: '<span class="PrimaryText">Chocobo</span><br><span class="SecondaryText"><font class="rdColor">= </font>Buddy</span>',
    m220: '<span class="PrimaryText">Hintergrundfarbe</span><br><span class="SecondaryText"><font class="rdColor">= </font>Graph Background *</span>',
    m223: '<span class="PrimaryText">Trennlinienfarbe</span><br><span class="SecondaryText"><font class="rdColor">= </font>Falls \'Trennlinien anzeigen\' aktiviert</span>',
    m224: 'Deckkraft Trennlinien',
    m32: 'Charakter Informationen',
    m33: 'Kampf Informationen',
    m34: 'Eingehender Schaden',
    m35: 'Heilung',
    m36: 'Anderes',
    m37: 'Rank und Name des Kämpfers',
    m214: 'Kämpfername.',
    m38: 'Klassen/Job-Icon des Kämpfers',
    m39: 'Kampfzeit des Charakters',
    m40: 'Gesamtschaden der Person dividiert durch die persönliche Kampfzeit.',
    m41: 'Die Kampfzeit.',
    m42: 'Gesamtschaden dividiert durch die Kampfzeit.<br><font class="rdColor">= </font>Diese Option ist weiter verbreitet als P.DPS',
    m43: 'Durchschnittlicher DPS der letzten 10 Sekunden.',
    m44: 'Durchschnittlicher DPS der letzten 30 Sekunden.',
    m45: 'Durchschnittlicher DPS der letzten 60 Sekunden.',
    m46: 'Durchschnittlicher DPS der letzten 180 Sekunden.',
    m47: 'Prozentualer Anteil am Gesamtschadens der Gruppe.',
    m48: 'Summe des verursachten Schadens.',
    m49: 'Prozentuale Treffergenauigkeit.',
    m50: 'Ausgeführte Aktionen.<br><font class="rdColor">= </font>Umfasst jede Auto-Attacke und Fähigkeit.',
    m51: 'Ausgeführte Aktionen, welche Schaden verursacht haben.',
    m52: 'Anzahl der Auto-Attacken oder Fähigkeiten welche nicht getroffen haben.',
    m53: 'Anzahl der Attacken, die keinen Schaden verursacht haben, aber kein Miss waren.<br><font class="rdColor">= </font>Umfasst: Widerstände, Reflektionen, Ausgeweichen, blocken, usw.',
    m54: 'Anzahl der kritischen Treffer.',
    m55: 'Prozentualer Anteil der kritischen Treffer.',
    m56: 'Höchster verursachter Schaden durch einen Angriff.',
    m57: 'Summe des erhaltenen Schadens.',
    m58: 'Summe der erhaltenen Heilung.',
    m59: 'Prozentualer Anteil an parrierten Treffern.',
    m60: 'Prozentualer Anteil an geblockten Treffern.',
    m61: 'Summe der verursachen Heilung dividiert durch die Kampfzeit.',
    m62: 'Prozentualer Anteil an der gesamten Heilung der Gruppe.',
    m63: 'Summe der verursachten Heilung.',
    m64: 'Summe der verursachten Heilung, Overheal und Schilde ausgenommen.',
    m65: 'Summe des Schadens, welcher durch Schilde der Healer absorbiert wurde.<br><font class="rdColor">= </font>Adloquium, Nocturnales Feld, ...',
    m66: 'Summe der Heilung, welche über 100% Gesundheit verursacht wurde.',
    m67: 'Prozentualer Anteil der Heilung, welche über 100% Gesundheit verursacht wurde.',
    m68: 'Anzahl der verursachen Heilungen (Umfasst auch Heilung von jedem Tick von HoTs wie Regena).',
    m69: 'Anzahl der Heilung, welche kritisch getroffen hat.',
    m70: 'Prozentualer Anteil der Heilung, welche kritisch getroffen hat.',
    m71: 'Größte verursachte Heilung.',
    m72: 'Anzahl der Zauber, welche negative Statuseffekte entfernt haben.<br><font class="rdColor">= </font>Medica, Päan des Hüters',
    m73: 'Summe der Lebenspunkte, die durch Kampffähigkeiten regeneriert wurden.<br><font class="rdColor">= </font>Blutbad, usw.',
    m74: 'Summe der Mana, die durch Fähigkeiten regneriert wurde.<br><font class="rdColor">= </font>Ätherfuss, Assise, usw.',
    m75: 'Anzahl der Tode.',
    m76: 'Anzahl der Treffer, die direkt getroffen haben.',
    m77: 'Prozentualer Anteil der Treffer, die direkt getroffen haben.',
    m78: 'Anzahl der Treffer, die direct und kritisch getroffen haben.',
    m79: 'Prozentualer Anteil der Treffer,  die direct und kritisch getroffen haben.',
};
    
